### ISSUE TITLE
Breaks scene directory if you have scenes in folders. 

### ISSUE THREAD

**Issue by Avitale34** [flamewave000/dragonflagon-fvtt#1]
Like title says if you have scenes that are in folders it screws up the module and the whole list becomes blank.

**Comment by flamewave000** [comment]
Sorry that's happening. You can find version 1.1 in the releases folder if it is causing you too many issues right now. I'm away this weekend, but I should be able to investigate the issue on Monday

**Comment by flamewave000** [comment]
Issue fixed in v1.3
