### ISSUE TITLE
DF Chat Enhancements: Idea: Icons and Colorization

### ISSUE THREAD

**Issue by ngPescado** [flamewave000/dragonflagon-fvtt#102]
_Idea_: **Icon/Token option use in chat boxes** as visual identifier. Top left placing next to Name. Options to combine same actor boxes could reduce clutter would reduce potential icon spam. Possibly click-linked to token on map.

_Idea_: **Colorization (background tint) of chat box** based on actor/player color. Provides more visual identifications when scrolling long chats.

Both options currently have old/outdated module solutions that address those two specific items. However, as a one shot Chat Enhancement package, I felt those two options would provide more power to the suite.

Apologize if already suggested ... couldn't find in project search.

**Comment by Shuggaloaf** [comment]
>Idea: Colorization (background tint) of chat box based on actor/player color. Provides more visual identifications when scrolling long chats.

Suggestion: Allow customizable color with Player color as _default_. Some player colors do not work well as a background and it would be useful to be able to select a different color or lighter tone in those cases.

**Comment by flamewave000** [comment]
So I don't think I will be doing the token artwork as the Chat Images module is well supported and performs this function well.

As for the background tint, I could look into implementing this functionality, along with maybe an additional field in the Player Configuration to set a custom colour for chat.

**Comment by flamewave000** [comment]
Hopefully this is working as you were hoping.

Chat Portrait has its own "Tint Message Background" feature, but this will do the same and work alongside it.

![image](https://user-images.githubusercontent.com/3588046/140839334-9b47ad3e-c5f2-4ec7-ad24-dfc59581eefa.png)

**Comment by Shuggaloaf** [comment]
Not a big deal but note "color" vs "colour" in user settings. Of course "color" is the only proper way to spell it. ;-)

**Comment by flamewave000** [comment]
> Not a big deal but note "color" vs "colour" in user settings. Of course "color" is the only proper way to spell it. ;-)

I'm actually Canadian and I use Canadian English (pretty much identical to `en-gb`) as the default so I'll be keeping my Us in my colours, flavours, and neighbours thank you haha. You can certainly provide a `en-us.json` if you'd like :+1:

**Comment by Shuggaloaf** [comment]
Find, keep your extra letters. ;-p 
I just realized though I may not have been clear in my message. You have both "color" and "colour" right next to each other in the user config window. But I guess the first 1 is core Foundry so... whatever, no big deal! Haha Thanks again.
