### ISSUE TITLE
DF Logger: Theatre Inserts

### ISSUE THREAD

**Issue by smoothingplane** [flamewave000/dragonflagon-fvtt#103]
**Conflicting Module(s)**
[Theatre Inserts
](https://github.com/League-of-Foundry-Developers/fvtt-module-theatre)

**Describe the conflict**
When the message appears in the chat if a player has selected a character in the "theater inserts" stage, the message appears on the screen for each player who has selected a character.

**Expected behavior**
The login message should not appear in the "stage".

**Comment by flamewave000** [comment]
This is an issue with Theatre Inserts. I'm sending OOC Whisper messages which should not be picked up in this manner, only IC and EMOTE messages should be collected for theatrical display. Either way, there's not really anything User Logger can do to prevent Theatre Inserts from displaying these messages.
