### ISSUE TITLE
DF Logger: for all the same message

### ISSUE THREAD

**Issue by smoothingplane** [flamewave000/dragonflagon-fvtt#104]
**Is your feature request related to a problem? Please describe.**
When a player joins the game, each other player sees a different message for that login.

**Describe the solution you'd like**
When a player enters the game, every other player displays the usual message.
This is because I translated the module and inserted funny phrases, it would be nice to be able to laugh at it together.

**Comment by flamewave000** [comment]
The module already does this. All users should see the same message for each user that enters the game. This is done by everyone having the same list of messages and a message ID is sent to everyone signed in to be displayed.

**Comment by flamewave000** [comment]
Not sure what you would have been seeing but I just tested it and I'm getting the correct result. Both users sign in and get the same messages.
![image](https://user-images.githubusercontent.com/3588046/114745088-5378c180-9d1c-11eb-9922-0dbde29ba101.png)

**Comment by smoothingplane** [comment]
[logger.zip](https://github.com/flamewave000/dragonflagon-fvtt/files/6313380/logger.zip)

I try to send you the modified version of dflogger I am using (I had to change the name otherwise TheForge automatically updates the module), maybe you can understand if I have modified something that creates this problem.

**Comment by smoothingplane** [comment]
Or maybe it's a problem with the forge, sometimes it doesn't even show messages (I'm doing tests)

**Comment by flamewave000** [comment]
I see the issue. In the Manifest, you removed the "socket" permission field. Without this permission, the module cannot communicate with the other clients, and therefore can tell everyone what the message is. Please add the following to somewhere in your `module.json` file:

```json
"socket": true,
```

This informs Foundry that the module uses the inter-client socket.
