### ISSUE TITLE
DF Manual Rolls: Add an option to bypass rolls with many die

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#107]
It would be nice if there was a prompt to optionally bypass a roll with many die, perhaps above 5.

For instance, if rolling HP for an Ancient Blue Dragon (meaning 26d20), pop up a confirmation to use manual rolls. If the user cancels manual rolling, roll all 26 d20s normally instead.

Or perhaps offer the user to roll all subsequent rolls normally after the first cancelled manual roll: Maybe i want to push the HP of the dragon up or down so i do the first 6 die manually by entering the rolls, but press cancel on the 7th prompt and thus cancels manual rolling for the subsequent dice rolls left.

**Comment by flamewave000** [comment]
I would love to do this kind of optimization, but unfortunately it would require me to completely modify the entire rolling system. It's not something I can do at the moment, especially with 0.8.x around the corner which has already overhauled Foundry's entire dice rolling system.

I really appreciate your feedback, and hope you can get by without for now. Just FYI, you can also use the Enter and Escape keys to select the OK  and Cancel buttons, if that helps any.

**Comment by plutoneld** [comment]
No worries! I suspected it would be a major undertaking.

Is the introduction of async rolls something that makes this viable, or is it simply just hard breaking up a dice expression to handle a part of it manually and a part randomly?

**Comment by flamewave000** [comment]
Mostly that second part. The system has various expression parsing that gets quite complicated. I'm currently trying to be light-weight and only patching the Dice Term part of the system. To do more, I would have to overhaul the whole Dice System in order to track how many dice are where and to offer skipping to entire groups. Async rolls are not changing the expression system, just making it so a dice roll can "wait" for the user to input a result.

**Comment by flamewave000** [comment]
Closing this since there's not much I can do for it at this time.

**Comment by flamewave000** [comment]
I'm happy to say this issue was actually resolved in the new v2.0. Async Rolls made it possible for me to provide a "Roll Total" column, as well as group all the dice for a roll together in a single prompt 👍🏽
