### ISSUE TITLE
Foundry 0.8.x Migration

### ISSUE THREAD

**Issue by flamewave000** [flamewave000/dragonflagon-fvtt#108]
# Modules Testing (Listed in order of planned migration)
1. ✔ Hotkeys (Already Functional)
1. ✔ Curvy Walls (Released 🎉)
1. ✔ Scene Enhancement (Released 🎉)
1. ✔ Settings Clarity (Already Functional)
1. ✔ Chat Enhancements (Released 🎉)
1. ✔ Quality of Life (Released 🎉)
1. ✔ User Logger (Released 🎉)
1. ✔ Manual Rolls

### ✔Curvy Walls
- ~~Multiple crashes in the console when using the tools.~~

### ✔Scene Enhancement
- ~~Scene tab is completely broken. This is likely due to the layout I'm using not being compatible with the new one.~~
- ~~Displays crashes in the console.~~

### ✔Chat Enhancements
- ~~Adventure Log: Works as is~~
- ~~Chat Edit: Works as is~~
- ~~Roll Types: Works as is~~
- ~~Chat Archive: There is an issue with the world name being undefined.~~

### ✔Quality of Life
- ~~Quick Roll and Auto-focus work fine~~
- ~~Folder Text colour is still customizable, but it does not show that colour in the folder.~~

### ✔User Logger
- ~~The `CHAT_MESSAGE_TYPE` is now inside a global `Const` class.~~

### ✔Manual Rolls
- ~~Crash in console~~

**Comment by adroste** [comment]
+1 for manual rolls 0.8 integration

**Comment by Jonwh25** [comment]
just logging this so there is a record of it. 

![image](https://user-images.githubusercontent.com/60674327/120399232-72dda500-c2f0-11eb-94fb-9ff1c2c90632.png)

**Comment by Jonwh25** [comment]
This one is for df logger:

![image](https://user-images.githubusercontent.com/60674327/120400195-49257d80-c2f2-11eb-8e09-568c85177f30.png)

**Comment by flamewave000** [comment]
@Jonwh25 Thank you for the error logs. I have completed work on the DF Scene Enhancements module and will be releasing shortly. I'm finished for the night and might continue tomorrow night some. Next up is Chat Enhancements 👍🏽

**Comment by flamewave000** [comment]
@adroste I did it! I got the manual rolls module updated and it works extremely well with the new Async Rolls! I'm quite happy with how it turned out, I'll be getting a release out tonight I think.
