### ISSUE TITLE
DF Curvy Walls: Rotation of segments

### ISSUE THREAD

**Issue by SalieriC** [flamewave000/dragonflagon-fvtt#109]
**Is your feature request related to a problem? Please describe.**
It seems that segments cannot be rotated. This means a rectangle will have the corners always in the upper left and right, lower left and right corner.

**Describe the solution you'd like**
A way to rotate at least the rectangle. This could be done by a drag point, a hotkey + mouse wheel, two buttons in the left controls or a combination.

**Additional context (Optional)**
![image](https://user-images.githubusercontent.com/1230041/115472992-2d32b480-a23b-11eb-943d-2886d29676eb.png)

**Comment by flamewave000** [comment]
Adding a rotation is something I would like to do for the rectangle and ellipse at some point. But in the meantime you might be able to get away with using the ellipse tool reduced to 4 segments. It has a rotation that could line that box up.

**Comment by flamewave000** [comment]
I don't see myself implementing this any time in the future. There is a lot of consideration going into native support for curved walls by the Foundry team, so I'll be doing mostly just maintenance for Curvy Walls.

**Comment by yorkshirelandscape** [comment]
This would be a tremendously useful feature. I'm sorry that you're not considering developing it. I suspect that Foundry's native support will still lag behind this implementation for a while even after it's rolled out. DF Curvy Walls is really fantastic.
