### ISSUE TITLE
DF Manual Rolls

### ISSUE THREAD

**Issue by Smart-Helper** [flamewave000/dragonflagon-fvtt#122]
Hello,

i wanted to ask if there is an improved Version of DF Manual Rolls coming or currently WIP as 0.8.X of Foundry introduced the asynchronous dice engine.

Like that you get an ingame window to enter the dice result, and maybe be able to combine all the dice you just rolled into one final sum (for example if your edgy rogue goes full sneak-attack, so you dont have to enter d6 one by one)

Greetings, :-)
Frank

**Comment by flamewave000** [comment]
The current plan, once I can get some spare time to do it, is as follows:
 - Fix issues with PF2 system (something changed in PF2 and manual rolls no longer works there).
 - Migrate module to 0.8.x
 - Investigate/integrate Async Rolling and better UI

**Comment by flamewave000** [comment]
Since 0.8.6 is now a stable release, I will be wrapping the PF2 fix into the migration.
