### ISSUE TITLE
DF Curvy Walls: No Longer Placing Walls

### ISSUE THREAD

**Issue by MrTranscended** [flamewave000/dragonflagon-fvtt#123]
**Module**
DF Curvy Walls v3.0.1 

**Describe the issue**
DF Curvy Walls incompatible with FVTT 8.06
After defining the area for the walls and then selecting the green check box to place the walls, nothing happens.

**To Reproduce**
1. Select Map
2. Select Wall Controls
3. Select Draw Walls
4. Select Ellipse Curve
5. Attempt to draw shape with mouse

**Expected behavior**
I expected to be able to draw a circle, then press the green "Apply curve to walls layer" button and have the walls created. 

**Screenshots (Attached)**
![curvywallsissue](https://user-images.githubusercontent.com/74849518/120401040-f77df280-c2f3-11eb-9eea-258c4d933e68.png)

**Comment by flamewave000** [comment]
DF Curvy Walls does not currently support 0.8.x. I do intend to upgrade all my modules for the new version of FoundryVTT as soon as I can get some spare time to get it done. I appreciate you taking the time to report this incompatibility. Please keep an eye on this ticket to see the general state and progress of the Dragon Flagon module migration to FoundryVTT 0.8.x
[Foundry 0.8.x Migration](https://github.com/flamewave000/dragonflagon-fvtt/issues/108)
