### ISSUE TITLE
Journal notes in the chat become unclickable if SceneEnhancement is enabled

### ISSUE THREAD

**Issue by spirritus** [flamewave000/dragonflagon-fvtt#124]
**Module**
DFSceneEnhancement 3.3.3
Foundry 0.8.6

**Describe the issue**
Journal notes in the chat are not clickable. 

**To Reproduce**
1. Have a chat card that links to an entry in the journal, e.g. the condition outputs from ccombat utility belt.
2. Click the entry in the chat card.
3. Observe JS error in the console

**Expected behavior**
The linked journal entry should open.
This worked perfectly with foundry 0.7.x.
Quite frankly I don't see the reason why this module interferes with chat at all.

**Screenshots (Optional)**
![DF-SceneEnhancementBug](https://user-images.githubusercontent.com/1154316/120888979-5f398380-c5fb-11eb-8ecb-3807f4b092a3.png)

**Comment by flamewave000** [comment]
Please see ticket #108

DF Scene Enhancement does not currently support 0.8.x. I am in the process of migrating my module's, but please be patient as it will take some time to get all 9 of my modules stable and released. I'm starting with the most popular module and working my way down, this one is ranked 3rd on that list.
