### ISSUE TITLE
DF Scene Enhancement: Module destroys layout of scene sidebar.

### ISSUE THREAD

**Issue by spirritus** [flamewave000/dragonflagon-fvtt#125]
**Module**
DF Scene Enhancement 3.3.3
Foundry 0.8.6

**Describe the issue**
This module works wonders with the scene sidebar in foundry 0.7.x. However, in 0.8.6 it produces not the expected result. See screenshot.

**To Reproduce**
1. Install and enable DF Scene Enhancement
2. Go to the scenes sidebar.

**Expected behavior**
Similar display to use within 0.7.x.
![DF-SceneEnhancementStyleError](https://user-images.githubusercontent.com/1154316/120889182-38c81800-c5fc-11eb-9dc6-f21d7c908885.png)

**Comment by flamewave000** [comment]
Please see ticket #108

DF Scene Enhancement does not currently support 0.8.x. I am in the process of migrating my module's, but please be patient as it will take some time to get all 9 of my modules stable and released. I'm starting with the most popular module and working my way down, this one is ranked 3rd on that list.

**Comment by spirritus** [comment]
cool thx
