### ISSUE TITLE
All scenes disappear and scene options

### ISSUE THREAD

**Issue by Avitale34** [flamewave000/dragonflagon-fvtt#131]
All scenes disappear with this module enabled. Screenshot for aid.
![image](https://user-images.githubusercontent.com/65961637/121738687-8ba44280-cac8-11eb-87ed-8a6fc20a7579.png)

**Comment by flamewave000** [comment]
Couple things I'll need to know:
- Which module are you using?
- Which version of Foundry are you using? 0.7.9, 0.7.10, or 0.8.6?
- Have you tried running with just my module on?

**Comment by pugnus666** [comment]
I found it was the mod Less Fog on my instance, which was installed as part of The Furnace. It was also screwing with other mods, not just yours.

**Comment by flamewave000** [comment]
Ok, thank you for the follow up. It sounds like they'll need to look into correcting their conflicts.
