### ISSUE TITLE
DF Manual Rolls: Initiative rolls doesn't prompt for input

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#133]
**Module**
DF Manual Rolls 2.0.0

**Describe the issue**
Rolling initiative from the Combat tracker doesn't prompt for inputs.

**To Reproduce**
Roll from Combat tracker, either "Roll NPCs", "Roll All" or individually. Neither produces a Manual Rolls dialog.

(No other modules active, FVTT 0.8.6)

**Comment by flamewave000** [comment]
Yeah this looks like foundry is still using Sync Rolls for initiative. I'll try patching the foundry core functions for this and see if I can get it working.

**Comment by flamewave000** [comment]
I was able to get it working :+1:
