### ISSUE TITLE
DF Manual Rolls: Add some more options for controlling manual rolling

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#136]
**Is your feature request related to a problem? Please describe.**
Using DF Manual Rolls in IRL games (yeah i know, who does that nowadays??), I mostly want to just enter the manual rolls made by PCs. While the new version does make it *a lot* easier to for instance roll HP for big creatures, it would streamline the rolling if i could just have PC rolls manually, and/or toggling manual rolls altogether.

(I realize that this workflow is a bit different than using it online, where the PC rolling is done in the individual clients rather than the GM.)

**Describe the solution you'd like**
There's a couple of options, all of which I think are good solutions:

- Toggle DF Manual Rolls on/off altogether, preferably by the most excellent module DF Hotkeys.
- Have an option to use Manual Rolls for PCs only.
- Have an option to bypass manual rolls by holding down some combination of keys (this is often used in other modules which changes the rolling mechanism and is perhaps risky to implement?)
- (a lot of other options I of course have not thought of)

In my opinion, I think the first option coupled with some visual indication of whether DF Manual Rolls is active or not, would be very nice. Perhaps changing the dice here in some way?

![image](https://user-images.githubusercontent.com/10401440/121861824-77e02280-ccfa-11eb-8436-2652ca9e6623.png)

**Comment by flamewave000** [comment]
While the d20 icon there would be a great place, I do know that it is already taken over by Dice-Tray. So instead, I'm going to add a toggle to the General Scene Controls instead
