### ISSUE TITLE
DF Manual Rolls: Rolling 20d4 and entering a total of 44 outputs a total of 59

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#140]
**Module**
DF Manual Rolls 2.1.0
(Other active modules include DF Hotkeys and libWrapper).

**Describe the issue**
Dice expression: `/r 20d4`
Entering a total of 44, actually outputs 59 to chat :rofl: 

Totals that **works**:
20
40
60

Totals that does **not work**:
30 (gives 40)
44 (gives 59)

**To Reproduce**
1. Roll `/r 20d4` in chat
2. Enter the total of 44
3. Observe the total of 59 being output

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/10401440/122391925-b7657380-cf73-11eb-8a22-90654ca0fbf3.png)

**Comment by flamewave000** [comment]
Thank you for this. It is a flaw in my distribution algorithm. I've got it fixed and will put an update out in a little while 👍🏽
