### ISSUE TITLE
DF Settings Clarity: Search Bar Misaligned

### ISSUE THREAD

**Issue by tjlanza** [flamewave000/dragonflagon-fvtt#141]
**Module**
DF Settings Clarity 3.1.0

**Describe the issue**
The size and position of the search bar doesn't actually match what is shown in the readme, which means it doesn't line up with Tidy UI.

Foundry 0.8.7 w/ DFSC 3.1.0
![image](https://user-images.githubusercontent.com/21128724/122564047-ee3e9680-d012-11eb-8eb6-632130d22fdf.png)

Readme from this git.
![image](https://github.com/flamewave000/dragonflagon-fvtt/raw/master/.assets/df-settings-clarity-search-tidy-ui.gif)

**To Reproduce**
1. Install and Activate DFSC 3.1.0 and Tidy UI 0.1.23
2. Go to "Configure Settings"
3. Observe

**Expected behavior**
They should match as shown in the readme.

**Addendum**
Ideally, the search bar would use exactly the same CSS descriptors as the Tidy UI bar, so that skinning modules will pick them both up and reconfigure them the same way.
![image](https://user-images.githubusercontent.com/21128724/122564903-e0d5dc00-d013-11eb-998f-8a7a31d9a187.png)

**Comment by flamewave000** [comment]
TidyUI does not have any associated CSS classes. Instead they are querying the element's ID. You'll have to open a ticket with whoever wrote your UI override module as they have added specialized styling just for TidyUI and would have to do the same for Settings Clarity. In the meantime, I will adjust the Settings Clarity layout to contain a generic "searchBox" CSS class that they can potentially target.
![image](https://user-images.githubusercontent.com/3588046/122583727-92323d00-d027-11eb-9079-f4294e92f6cb.png)
