### ISSUE TITLE
DF Curvy Walls: Can no longer use ctrl to continue from existing wall segment

### ISSUE THREAD

**Issue by OfficerHalf** [flamewave000/dragonflagon-fvtt#142]
**Module**
DF Curvy Walls v3.1.0, Foundry 0.8.7
Tested on Firefox and Edge (Chromium).

**Describe the issue**
As title. Cubic and Quadratic bezier curves can no longer be placed from an existing point, only standalone. Instead, trying to ctrl-drag produces a curved wall separate from the existing point. I'm guessing this is related to #112. It seems to not be detecting the drag, only the click.

**To Reproduce**
1. Have an existing wall segment. It doesn't seem to matter if it was created with Curvy Walls.
2. Hold Ctrl.
3. Click and drag to try and place a cubic/quadratic curved wall from an existing point.
4. See that a wall has been placed and dragging has stopped prematurely.

**Expected behavior**
Should be able to click and drag to create a new wall from an existing point.

**Screenshots (Optional)**
![Curvy](https://user-images.githubusercontent.com/4851889/122629088-5c717080-d088-11eb-90bc-389cb1614824.gif)

**Comment by flamewave000** [comment]
Hmm.. so that's an unexpected side effect of the new tool drop. Maybe I'll make it configurable and default to the Alt key.
