### ISSUE TITLE
DF Chat Enhancements: Chat Messages are dublicated

### ISSUE THREAD

**Issue by Muwak77** [flamewave000/dragonflagon-fvtt#144]
V 3.1.0

Chat-Messages and Die-Rolls are executed twice. This only seems to happen in conjunction with The-Dark-Eye Ruleset

**To Reproduce**
Just enable the Module while using the TDE-Game-System and type anything into the chat. It will execute twice

**Expected behavior**
Command should only be shown once

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/64545711/122690607-d6415f80-d22a-11eb-9a92-be20dbd4bcd6.png)

**Comment by Muwak77** [comment]
After some additional testing, i found, that the conflict is caused by the underlying Library:Chat Commands. I'll post the issue there, sorry for the trouble.

**Comment by flamewave000** [comment]
Hey no problem. I'm just happy you were able to figure this one out 👍🏼
