### ISSUE TITLE
DF Chat Enhancements : Chat card merge

### ISSUE THREAD

**Issue by drdwing** [flamewave000/dragonflagon-fvtt#145]
I think it would be good to add the Chat Merge module's function to this module after seeing Edit Sent Message.
Chat Merge module doesn't seem to be maintained.

**Comment by flamewave000** [comment]
I'll have to take a look at the other mod and make sure it's no longer maintained. Don't want to step on any toes 👍🏼

**Comment by drdwing** [comment]
Ok, Thank you!! 👍

**Comment by flamewave000** [comment]
ok, so I've got this working pretty well I think

![image](https://user-images.githubusercontent.com/3588046/123880222-32ce0a00-d910-11eb-90e4-b9a2be1e9f53.png)
