### ISSUE TITLE
DF Chat Enhancement: /log or /gmlog broken in 0.8.8

### ISSUE THREAD

**Issue by Jonwh25** [flamewave000/dragonflagon-fvtt#148]
**Module**
DF Chat Enhancement 3.1.0 

**Describe the issue**
Can't use /log or /gmlog to log anything. Getting the following error in the console log

![image](https://user-images.githubusercontent.com/60674327/123384693-8ffd4080-d549-11eb-931f-0274ef1ac404.png)

**Comment by flamewave000** [comment]
I'm not receiving this issue. This was likely an issue with the [Library: Chat Command](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib) that I am using. They've had some updates as recently as yesterday and I don't appear to be able to reproduce your issue.

Please let me know if you are still seeing the issue. If so I'll reopen and see if I can find the problem.

**Comment by Jonwh25** [comment]
Got it working. I uninstalled the library chat commands, then deleted and recreated the adventure and gmlog journal entries and it works now.  Thanks
