### ISSUE TITLE
DF User Logger: chime.mp3 Not Found

### ISSUE THREAD

**Issue by tjlanza** [flamewave000/dragonflagon-fvtt#150]
**Module**
DF User Logger 1.6.0

**Describe the issue**
404 error on /modules/df-logger/sounds/chime.mp3
![image](https://user-images.githubusercontent.com/21128724/123570600-8caac480-d796-11eb-873a-77fc6d815e4c.png)

I completely removed and reinstalled the module, just to be sure.

**To Reproduce**
1. Upgrade DF UL to 1.6.0
2. Log in, expecting sound.
3. Hear nothing.
4. Check console.

**Expected behavior**
The sound should be there.

**Screenshots**
The /sounds directory does not exist.
![image](https://user-images.githubusercontent.com/21128724/123570498-50776400-d796-11eb-8766-5145a67f6d77.png)

I also get the following error, but I suspect it's on account of the missing file.
![image](https://user-images.githubusercontent.com/21128724/123570552-743aaa00-d796-11eb-9d33-5b7d7d634892.png)

**Comment by flamewave000** [comment]
Thanks for reporting this. I'll take a look asap 👍🏼

**Comment by Jonwh25** [comment]
@flamewave000   Yeah it looks like this is due to the sounds directory not being included in the zip file.  I confirmed by uninstalling the module and reinstalling and sure enough, the directory is no longer part of it.

**Comment by flamewave000** [comment]
Yeah, it looks like I accidentally broke the sound directory bundling phase in my build script so it didn't include the file with the produced ZIP file. I'll push a bug fix release with the file included 👍🏽
