### ISSUE TITLE
DF Manual Rolls: Throws errors in console on all(?) chat messages

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#152]
**Module**
DF Manual Rolls 2.2.0

**Describe the issue**
It seems DF Manual Rolls tries to find rolls and terms on all chat messages (understandably), but fails not so gracefully when no roll and terms can't be found.

**To Reproduce**
1. Type a text chat message in chat, and observe Dev Console

**Expected behavior**
"Fail" gracefully, do not try to parse roll/terms.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/10401440/123736038-a6383300-d8a0-11eb-9906-796a5549ee59.png)

**Comment by flamewave000** [comment]
This seems like an issue I didn't catch from the original 0.8.x release. My boolean logic was broken, fixed now and will push a bug fix release. Thanks for spotting this 👍🏽
