### ISSUE TITLE
DF Scene Enhancement

### ISSUE THREAD

**Issue by DukeXray** [flamewave000/dragonflagon-fvtt#153]
**Module**
DF Scene Enhancement V3.4.0

**Describe the issue**
Create new scene and create new folder button is missing from the scenes tab.

**To Reproduce**
Should be pretty easy. Enable the module. I disabled all other modules that were not a dependency.

**Expected behavior**
To be able to create new scenes

**Screenshots (Optional)**

![image](https://user-images.githubusercontent.com/86801489/124177290-404cd680-da6d-11eb-81cf-dcb8d12e3968.png)

**Comment by flamewave000** [comment]
Just took a look at this. It looks like this only happens if you do not have any scenes in the world.
