### ISSUE TITLE
DF Active Lights: Dark UI for SF and Ernie's Modern UI

### ISSUE THREAD

**Issue by Iankid** [flamewave000/dragonflagon-fvtt#159]
Dark UI for SF
Ernie's Modern UI
Very possibly other UI mods

Because some of this mod's UI is locked in, the UI changes from the UI mods create a visual conflict. making it hard to use this mod.

I'm hoping, either this mod should fully let the UI mods interact with its UI, or it should lock down all aspects of it's UI

![lightsmod-UI](https://user-images.githubusercontent.com/60759323/125915196-ecc48122-9399-4a7f-80e7-036003d0f210.png)

**Comment by flamewave000** [comment]
So this is not a "locked in" thing, but rather the fact that these other UI overhaul mods just don't have CSS to style my new DF Active Lights module (as they would have for many other mods). I could strip out some of the styling, but it would be removing the visual segregations of the elements and making them look cluttered, and it would likely have to apply to everyone and not just for your UI overhauls.

**Comment by flamewave000** [comment]
This module is working as expected for Foundry Core, please open a ticket with the authors of those UI overhaul modules to have them include styling for DF Active Lights.
