### ISSUE TITLE
DF Chat Enhancement: Self speaking/rolling

### ISSUE THREAD

**Issue by uniwars** [flamewave000/dragonflagon-fvtt#161]
Hello !

Actually there is no way to self speak or really self roll (the ??? roll is visible by GM).

Would that be possible to add a new rolling button "Secret" or "Invisible" roll or something like that, that would be like the /talktomyself command of Roll20, letting the player roll or send message that only him can see without sending roll notification/sound/??? to other player/GM and same with chat message ?

Thanks for your work.

**Comment by flamewave000** [comment]
So in core Foundry you can whisper to yourself, and the GM cannot see that whisper.

`/w [Test Player] Hello World` this will whisper to "Test Player". If you are Test Player, then the whisper will go to you and no one will see the message.

As for the rolling, there are modules that provide properly private rolls. For GM Rolling, there is the module [Hide GM Rolls](https://foundryvtt.com/packages/hide-gm-rolls). I don't currently plan to modify how rolls are displayed as that is heavily modified by all of the roll automation modules out there.
