### ISSUE TITLE
DF Chat Enhancement: Add ability to Copy Formatted Chat Text

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-fvtt#163]
Formatted text in the chat window cannot be selected (and therefore can't be copied). 

**Steps for testing:** Type `<b>Hello World!</b>` in chat and hit enter. You will not be able to select the bolded text. 

Would like to see a feature added to allow formatted chat text selecting/copying. There is another mod out there called FVTT-copy-chat that has similar functionality but (1) is older and may no longer work (not sure didn't install it) and (2) it seems like a natural fit for this mod. Which helps keep mod count down for those of us already using DFCE. the other mod adds a little button to click and copy but if there is a way to just allow text to be highlighted/selected manually that would be great as we could select only what we need/want (not sure if that's easier or harder).

For now a workaround is export to Adventure Log and then the text is able to be copied, but of course this is a bit tedious to have to go through the extra steps. 

Thanks Flamewave!

**Comment by flamewave000** [comment]
I see the module has been updated within the last month. I can investigate to see if this can maybe be done better though. I agree that selecting formatted text with the mouse cursor would certain be preferable vs copying the entire message.

**Comment by Shuggaloaf** [comment]
> I see the module has been updated within the last month

I didn't even catch that. It has "Tested on Foundry VTT 0.7.5" under Compatibility and that's what I was going off of. Checking the module.js file though I do see the line:  "compatibleCoreVersion": "0.8.8"

But yeah, it sounds like you also prefer the same method/enhancements I'd like to see. Plus not sure about you, but for me, with like 70 mods, not having to install another is always nice! 

I appreciate the consideration of this enhancement!
