### ISSUE TITLE
DF Chat Enhancement: When Disabling Mod it may Disable LibWrapper

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-fvtt#164]
Hi Flamewave, when DFCE is disabled, you get the standard popup window asking if you want to disable the dependencies. The only one listed is _chat commands. If you click yes, LibWrapper is also disabled, even though it is not listed in the popup.

**Comment by flamewave000** [comment]
So this is not a module thing but something that Foundry does itself. It's a bug in the Core. I declare my dependencies in the module's manifest, and Foundry solely manages those dependencies for enabling/disabling them. That prompt is being created by the Foundry Module manager.

**Comment by Shuggaloaf** [comment]
Is Core deciding what should be listed on that window or is that from where you declare your dependencies? Shouldn't LibWrapper at least be listed on that window, I know it is with other mods. Just trying to understand what handles what.

**Comment by flamewave000** [comment]
So Core is the one that decides what gets listed, and it does so based on the listed dependencies. I have both Chat Commands and libWrapper listed.
![image](https://user-images.githubusercontent.com/3588046/128030083-61bc7097-2df6-4e97-b633-41b84562dffe.png)

**Comment by Shuggaloaf** [comment]
Thanks for the explanation. Yeah that's odd, I tested out other mods that have LibWrapper as a dependency and they don't even mention it at all. Something funky is def going on with LW/Core. 

Thanks Flamewave!
