### ISSUE TITLE
DF Chat Enhancements: Reduce Roll Type Buttons Height

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-fvtt#165]
Hi Flamewave, Sorry to be bombarding you with issues/requests! I know this is more of a cosmetic preference thing, but I would like to request the button height be reduced for Roll Type buttons. Not the icons themselves, they should remain the same size, but the button "boxes" themselves. There's a lot of padding there. Perhaps the height could be brought down to be within the red lines in this pic:
<img src="https://user-images.githubusercontent.com/79543184/127679833-18ba9223-3867-41c4-ab97-317f782e23a1.jpg" width="50%">

_Preferably_, however, I would remove the background altogether and just use a "highlight on hover" method with the currently selected mode having the icon color changed (or icon highlight color). Or, if easier/preferred, use a button background like the core toolbar button backgrounds
(Not sure if you remember but I had put in a request on Discord (I go by "Earl") a few weeks back for Core Foundry to actually add buttons like yours, and you pointed me to DFCE. I had added a mock-up image on there. I will dig it up and post it here later to help visualize what I'm saying)

Again I know this is a cosmetic thing and everyone's preferences are different but I do think this would give the buttons a nice polished look. (Maybe do a mock-up and put it out as a poll or something? - Or just tell me to screw off :-p )

Thanks Flamewave!

**Comment by flamewave000** [comment]
So there is an option that sets the other two buttons to look the same as the roll-type buttons to make the whole row look good.
![image](https://user-images.githubusercontent.com/3588046/127684332-448123a8-e849-4e51-9133-a83097b285dc.png)
![image](https://user-images.githubusercontent.com/3588046/127684395-1d945cd6-c3ca-4e5d-8a51-e6ccdb0a27ec.png)


I specifically designed these buttons as they are for Accessibility reasons. The colours themselves are selected from a range of colours that provide enough contrast with the icon, and are of colours that can be seen by those who are colour blind. I'd prefer not to change them.

**Comment by Shuggaloaf** [comment]
Hey Flamewave, yeah I knew about that option to make them all look the same. It wasmore about not liking the parchment color background of the buttons, not the green/yellow/orange/red highlights. But I'm guessing the parchment background is part of the accessibility reasons. I also figured this was a long shot as it was a personal preference thing, but figured it doesn't hurt to ask! 

Is the button height itself part of accessibility? 

I actually had played around with the CSS and made them a bit shorter but I noticed that the icons stay lower even when adjusting button height. I don't mind playing around with the files after each update but would you be able to point me to what I need to adjust to raise the icons themselves up a little? If not no worries, again, doesn't hurt to ask. :-)

**Comment by flamewave000** [comment]
This will shrink the button height from 36px to 30px. For centering the icon, you have to adjust the `line-height` of the `<i>` element

```css
#dfcp-rt-buttons button {
	min-height: 30px;
	max-height: 30px;
}
#dfcp-rt-buttons button i {
	line-height: 24px;
}
```

**Comment by Shuggaloaf** [comment]
Hey Flamewave thanks for the help. I'm not going to keep bugging you about it but just wanted to let you know I couldn't get it to work for some reason. `#dfcp-rt-buttons button i{ }` doesn't have a `line-height` element, but it does have height. I tried adding `line-height: 24px;` in addition to `height`, tried adding it and removing `height` and not adding it and just changing `height` to a lower value (and reloading after each change). None seemed to work. 

Like I said, don't worry about it, you've spent enough time on this but just wanted to say thanks and let you know the result.
