### ISSUE TITLE
DF Curvy Walls: Monk's Wall Enhancment conflict

### ISSUE THREAD

**Issue by patrickburk1988** [flamewave000/dragonflagon-fvtt#169]
**Conflicting Module(s)**
Monk's Wall Enhancment

**Describe the conflict**
libWrapper throws an error whenever you begin to place a cubic/quadratic bézier curve, elliptical curve, or rectangle provided by this module. Per libWrapper: `libWrapper: Potential conflict detected between module 'df-curvy-walls' and module 'monks-wall-enhancement'. Module 'df-curvy-walls' did not chain the wrapper for 'WallsLayer.prototype._onDragLeftCancel'.`

**Additional context (Optional)**
- The error isn't thrown when using the regular wall tool or the freehand wall tool provided by Monk's Wall Enhancement.
- I've not noticed any behavioral wonkiness beyond the libWrapper error, so this conflict may be safe to ignore?

**Comment by flamewave000** [comment]
I would say it is likely safe enough to ignore. I don't think it is something I can really correct as we both are overriding the same part of the system.
