### ISSUE TITLE
DF User Logger: console error with AudioNode / Libwrapper

### ISSUE THREAD

**Issue by Jonwh25** [flamewave000/dragonflagon-fvtt#171]
DF User Logger v1.6.2
DND5e v1.4.2
Foundry 0.8.8

Issue:  The console is throwing this error when logging in. It doesn't seem to affect much but it does it when each person connects to the game.

![image](https://user-images.githubusercontent.com/60674327/129589723-f3cc3229-9030-4fce-a7bb-6ad5d5f97a8c.png)

**Comment by flamewave000** [comment]
This is likely because I am attaching a Sound to the message which is expected to play when the message gets posted. I'm not sure why there would be an error though because that is all a Foundry Core feature. Might be a bug introduced in 0.8.x since this was definitely not happening in 0.7

**Comment by flamewave000** [comment]
This appears to be an issue with Monk's Little Details. The exception appears to get thrown in the `chatLogNotify` call of that module and not DFUL
