### ISSUE TITLE
DF User Logger: Manage Messages Display doesn't scroll

### ISSUE THREAD

**Issue by Jonwh25** [flamewave000/dragonflagon-fvtt#172]
DF User Logger v1.6.2
DND5e v1.4.2
Foundry 0.8.8
Chrome 92.0.4515.131

Issue:  I can't scroll to the bottom to edit / view the chat messages in message management. Even if I resize I can't make my screen large enough to see the bottom. 

**To Reproduce**
1. Go to game settings
2. Click on configure settings
3. In the module settings tab scroll down to DF User Logger
4. Click Manage Messages
5. There is no ability to scroll down.

**Expected behavior**
I should be able to see all the messages to be able to view / edit / disable

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/60674327/129590808-5775cb53-6af8-4615-bbf3-62a65f5ce8f6.png)

**Comment by flamewave000** [comment]
Yikes! This looks like it is a module conflict. The UI for that window is supposed to look very different. Could you try using Find the Culprit to find it?

**Comment by Jonwh25** [comment]
Looks like the culprit is Library: DF Hotkeys

Hey I hear that guy writes some good stuff.

**Comment by flamewave000** [comment]
Hah, well I haven't the foggiest idea why that would conflict, but I'll take a look when I get back from vacation 👍🏼for now I guess the work around is to temporarily disable Hotkeys while you update the messages
