### ISSUE TITLE
DF Chat Enhancements: Override client module settings to use server settings

### ISSUE THREAD

**Issue by ralph2190** [flamewave000/dragonflagon-fvtt#173]
**Is your feature request related to a problem? Please describe.**
I recently customized module settings for DF chat enhancements and found a combo of settings I liked, but was surprised to find out that it didn't propagate to my player clients. I guess it's not immediately clear which settings propagate out to the clients and which ones stay on the server. For instance, I added chat headers to the merged messages but recently discovered that the players don't have that checkbox enabled.

**Describe the solution you'd like**
I would love for a setting/checkbox that allows the clients to mirror the settings that the server uses.

**Describe alternatives you've considered (Optional)**
There really doesn't seem to be a good workaround other than having the players all navigate to the settings page and use my settings. I would much rather have the players do nothing and consume the module based on the settings I modify.

**Comment by flamewave000** [comment]
To avoid this kind of confusion in the future, I highly recommend one of my other modules [DF Settings Clarity](https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-settings-clarity)

**Comment by flamewave000** [comment]
I don't intend to change the scopes for these settings. I will recommend you look into using the module [SocketSettings](https://foundryvtt.com/packages/SocketSettings). It allows you to push your settings choices to your connected players.

**Comment by ralph2190** [comment]
@flamewave000 thank you so much for informing me about that module. I can confirm that it is a good workaround!
