### ISSUE TITLE
DF Chat Enhancement: Print Chat Archive into HTML Format

### ISSUE THREAD

**Issue by jbblily** [flamewave000/dragonflagon-fvtt#175]
**Is your feature request related to a problem? Please describe.**
I like the Chat archive feature. However, sometimes I want to add some styles on chatlog, in order to make it more comfortable to read. Currently, only pdf can be downloaded, and default foundry's style is not that good to read I think.

**Describe the solution you'd like**
I think it would be great if chatlogs can be printed out as a html format, so that users can edit it as they want.

When printable stream module was available, I extracted html sources and back up as a page. 
Please consider about this feature. Thank you!

**Comment by jbblily** [comment]
Oh, sorry. 
I should have said that I used to use [printable stream](https://github.com/ShoyuVanilla/FoundryVTT-Printable-Stream) module until it is depricated. So basically, I want the feature just similar as it.

It prints out chatlog as a separate tab, styles all adapted. So I can just copy all the page contents, and edit the html sources if it breaks. 

This is my example page using this method. https://crownel.github.io/2021-05-26-fvtt/

Or... I think it is just fine printing out raw html, so I can manually edit the css and stylings.

Thank you for your work.

**Comment by flamewave000** [comment]
@jbblily hopefully this is what you were looking for:
![image](https://user-images.githubusercontent.com/3588046/140869374-df1f895e-119c-4f53-bf10-2b74da5a3b11.png)

It downloads the message list from the archive as plain HTML withc all of the CSS classes and inline-styles still in place. That way you can bind any CSS you want to it to make it look however you want.
![image](https://user-images.githubusercontent.com/3588046/140869478-70582af2-9880-4253-84d6-add872f4142a.png)
