### ISSUE TITLE
DF Manual Rolls: Rolls from inline jorunal/item texts not prompted for manual input

### ISSUE THREAD

**Issue by MichalGolaszewski** [flamewave000/dragonflagon-fvtt#184]
**Module**
DF Manual Rolls 2.2.2

**Describe the issue**
Rolls embeded in journal entries/items text descriptions are not being prompted for manual die input.

**To Reproduce**
1. Create a journal entry / item
2. Embed a roll command into the text, eg. [[/r 1d4]]
3. Close the editor and click the roll button
4. The roll happens without a prompt for manual input

**Expected behavior**
After clickin the roll button a prompt for manual die input should appear.

**Comment by plutoneld** [comment]
I can't reproduce this with the DF Manual Rolls (v2.3) and FVTT v9.

**Comment by flamewave000** [comment]
@MichalGolaszewski this was likely an issue where Foundry's inline rolls were not using the new Async Roll system in 0.8.x. If you have not moved up to V9, you can try enabling Legacy Mode in the DF Manual Rolls settings.
