### ISSUE TITLE
DF Curvy Walls: No gulpfile found

### ISSUE THREAD

**Issue by Luterium** [flamewave000/dragonflagon-fvtt#186]
Once you download the package and go to /path/to/repo/dragonflagon-fvtt/df-curvy-walls/ as specified on the README, you install gulp as told and continue to do npx gulp, but there's no gulpfile.js on the folder so that it is able to run. How is one supposed to fix this?

**Comment by flamewave000** [comment]
There is a single gulpfile in the root directory that all of the modules use for compilation. Please use the npm scripts that are defined in the package.json

**Comment by flamewave000** [comment]
I haven't updated that part of the README and it still refers to how I used to do builds with a gulpfile in every module's folder. It was way too much to manage.
