### ISSUE TITLE
DF Curved Walls: Nodes are obnoxiously big

### ISSUE THREAD

**Issue by CatbotTsumi** [flamewave000/dragonflagon-fvtt#190]
**Module**
DF Curvy Walls v3.2.1

**Describe the issue**
The tool nodes (and the font size) are obnoxiously big. See screenshot: https://i.imgur.com/EMaoEBK.png

**To Reproduce**
1. Use one of the module's tools.
2. Have a hard time positioning things accurately due to the visual size of the tool handles.

**Expected behavior**
Tool handle nodes be as big as the wall nodes. And the font size to be around half the size 

**Screenshots (Optional)**
![Image](https://i.imgur.com/EMaoEBK.png)

**Comment by flamewave000** [comment]
I can maybe look at adding the ability to scale the handles and text size to a Small/Medium/Large.
