### ISSUE TITLE
DF Quality of Life: Highlight targets during template preview

### ISSUE THREAD

**Issue by tposney** [flamewave000/dragonflagon-fvtt#193]
**Is your feature request related to a problem? Please describe.**
It would be nice it template targeting was active during template preview.

**Describe the solution you'd like**
Hooking "game.dnd5e.canvas.AbilityTemplate.prototype.refresh" and doing the targeting part of the UPDATE_TARGETS should be sufficient, it does need to be WRAPPED rather than override.

**Comment by tposney** [comment]
Many thanks works perfectly. midi now has an option to hand over AoE targeting to df-qol.

**Comment by flamewave000** [comment]
Cool :+1:
