### ISSUE TITLE
DF Quality of Life: Styling Controls for Adventure Log

### ISSUE THREAD

**Issue by weepingminotaur** [flamewave000/dragonflagon-fvtt#197]
A feature request for a future version: the ability to control how messages saved to the Adventure Log are displayed. Right now, it appears in a monospace font, with color differentiations (green for whispers, etc.) that the GM can't control, the player name appears next to the character name even if the two are the same, and so on. Would be great to be able to style that log and make it pretty!

**Comment by flamewave000** [comment]
So there's not really an easy way to provide styling to these messages. You would need to define custom CSS. I unfortunately don't have the time to make a complex stylizer for this feature.

**Comment by flamewave000** [comment]
If you feel like trying your hand at some CSS, you can find the CSS for this particular feature here:
https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-chat-enhance/css/adventure-log.css
