### ISSUE TITLE
DF Chat Enhancements: Archive breaks if changing world path

### ISSUE THREAD

**Issue by saif-ellafi** [flamewave000/dragonflagon-fvtt#205]
**Module**
DF Chat Enhancements 3.4.1

**Describe the issue**
This is very minor, but sharing it for the record since it just happened to me. I changed the world folder name, and thought it would still work since I changed the Archive location (actually it did automatically I think). However, somewhere in `settings.db` there was a hardcoded path of the original world path location to the Chat Archive. So I couldn't any longer open the archive.

**To Reproduce**
1. Create a world
2. Create some chat and archive it
3. Change the world folder name and world.json file to the new file path
4. Open world and open the archived chat
5. An error is thrown (sorry, I lost the error now - but it is somewhat related to the archive path not found)

Thanks!!

**Comment by flamewave000** [comment]
Unfortunately this is not something I can easily correct. You best option would be to shutdown you Foundry instance, make a backup of your `settings.db` file called `settings.db.bak`, then open the `settings.db` file. Then search for any instance of your old world path and replace it with your new world path. Save the file and start up your foundry server.

If anything goes wrong, simply shutdown foundry and restore the settings backup by deleting the `settings.db` and renaming the `settings.db.bak` to `settings.db`.
