### ISSUE TITLE
DF Chat Enhancements: Cannot edit a message more than once!!!

### ISSUE THREAD

**Issue by saif-ellafi** [flamewave000/dragonflagon-fvtt#206]
**Module**
DF Chat Enhancements 3.4.1

**Describe the issue**
After editing a chat message once, the **Edit Message** option is gone!

**To Reproduce**
1. Write a chat message
2. Right click, edit it to something different
3. Right click on the edit message
There is no longer an Edit Message button!

**Expected behavior**
To be able to edit many times!

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/27952699/141377122-727af36c-0a37-4f2a-bfb9-5f623d957d19.png)

**Comment by saif-ellafi** [comment]
If it helps at all, @flamewave000  my theory is that Chat Messages that contain some sort of HTML formatting are the ones that lose the editing capabilities. If you send a message with `<b>Some Bold Text</b>` then also the Edit button won't appear.

**Comment by saif-ellafi** [comment]
New lines in chat would also cause the Edit Message to go away.

**Comment by flamewave000** [comment]
The HTML is not an issue, there is a setting that can be turned off that prevents editing messages with HTML. This is meant to be a "safety" in the event a message contains a information the GM doesn't want edited.
![image](https://user-images.githubusercontent.com/3588046/141874835-e7e6c6ae-dc48-4281-9884-e3c11253fad0.png)

**Comment by flamewave000** [comment]
I found the issue. The added "edit" flag on the message is causing the filter to activate since it is HTML. I'll get this corrected :+1:
