### ISSUE TITLE
DF Chat Enhancements randomly hides messages and rolls [Fixed already?]

### ISSUE THREAD

**Issue by KJTailor** [flamewave000/dragonflagon-fvtt#209]
**Module**
Chat Enhancements v3.4.1 (potentially older?)

**Describe the issue**
Last session me (GM) and one of my players could not cast rolls into the chat.

The other 4 players had no issues. After carefully deactivating all roll or chat related mods one by one, it turned Chat Enhancements was the culprit. Given the most recent update not even 4 days ago, it is entirely possible that the update to 3.4.1 fixed it already. Interestingly, it seemed that the rolls were simply 'hidden', as deactivating Chat Enhancements resulted in them being displayed, where they were rolled.

The error does not persist for now, but I thought it might be something worth mentioning.

**Comment by flamewave000** [comment]
This may be related to #203. Could you retest this?

**Comment by KJTailor** [comment]
I tried replicating the error, but it didn't seem to work out. Adventure log works fine. Disabling and re-enabling it doesn't cause the error mentioned in #203.

**Comment by flamewave000** [comment]
Is it safe to close this ticket?

**Comment by KJTailor** [comment]
Yes. I just wanted to point out a possible issue, but couldn't replicate it. Thanks for your time.
