### ISSUE TITLE
DF Curvy Walls: Minimal UI

### ISSUE THREAD

**Issue by CardinalRed1** [flamewave000/dragonflagon-fvtt#211]
**Conflicting Module**
[Minimal UI by Saif](https://github.com/saif-ellafi/foundryvtt-minimal-ui)

**Describe the conflict**
The additional buttons introduced with curvy walls are not integrated with Minimal UI.

**Expected behavior**
Small buttons integrated in the style of minimal UI.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/93453050/141735904-8e926b51-f2b0-4e8d-b8d2-5cb076e27387.png)

**Additional context (Optional)**
This is a relatively minor/aesthetic issue. Wasn't sure to post this to here, Minimal UI, or both. The autohide and fade effects do integrate with Minimal UI though.

**Comment by flamewave000** [comment]
This is typically up to Minimal UI to change. Any UI overhaul module typically needs to integrate other modules into themselves. If the developer has any issues setting the styles, I'm more than happy to assist.
