### ISSUE TITLE
DF QOL: Don't target in a template if there is a wall

### ISSUE THREAD

**Issue by Zamrod** [flamewave000/dragonflagon-fvtt#227]
If there is a wall between the origin of a template and a target, it should stop targeting. Could you add a feature to only target those who aren't blocked by walls?

**Comment by GhostwheelX** [comment]
Also, perhaps have a button you can hold where it cancels this behavior, since some spells (such as Fireball) go around corners.

**Comment by flamewave000** [comment]
Unfortunately I don't think I have the time to try and figure out how to integrate wall detection into my already very complex grid highlighting. I would recommend maybe using the [Walled Templates](https://foundryvtt.com/packages/walledtemplates) module as it does not conflict and updates the template border accordingly.
