### ISSUE TITLE
DF Chat Enhancement: Editing an HTML Log Entry Can Cause Duplicates of New Entries

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-fvtt#236]
**Module**
DF Chat Enhancement ver 1.5.1 (also happening since at least 1.4.1)

**Describe the issue**
When an HTML chat entry has been added to a Log, if that entry is edited within the log and a hard `<ENTER>` is used, it creates a `</section>` before each new line. 
When adding a new entry after that, either HTML or Plain Text, The entry gets duplicated to where there is a section end. 

For example entry has this code:
```<section>
<h2>GM Only Adventure Log</h2>
<section class="df-adventure-log">
<p><code><span class="dfal-ts">Renewfest 06, 1499 19:34:35</span></code>&nbsp;(<span class="dfal-na">Gamemaster</span>)&nbsp;</p>
<h2><strong>Adrios Boston</strong></h2>
<strong>Human, Male</strong><br /><em>Beggar</em><br /><br />&bull; Average Height and Bulky build<br />&bull; Pox-Marked complexion<br />&bull; Childish Green eyes<br />&bull; Wavy, Shoulder-Length, Chestnut brown Hair,<br />&bull; Duck-Tail-Beard<br />&bull; Enthusiastic demeanor<br /><br />&bull; Quirk in Lip / Right<br />
<p>&nbsp;</p>
</section>
<hr /></section>
```

and looks like this:
<img src="https://user-images.githubusercontent.com/79543184/145689966-f4b25f3c-6e27-4a3a-bc09-ae6daa3d69bf.png" width="30%"/>

Now if I edit this, let's say to add 2 lines of description text below the "_beggar_" line. If I use a hard Enter for each new line the code looks like this:
```<section>
<h2>GM Only Adventure Log</h2>
<section class="df-adventure-log">
<p><code><span class="dfal-ts">Renewfest 06, 1499 19:34:35</span></code>&nbsp;(<span class="dfal-na">Gamemaster</span>)&nbsp;</p>
<h2><strong>Adrios Boston</strong></h2>
<strong>Human, Male</strong><br /><em>Beggar</em></section>
<section class="df-adventure-log">Description Text Line 1</section>
<section class="df-adventure-log">Description Text Line 2<br /><br />&bull; Average Height and Bulky build<br />&bull; Pox-Marked complexion<br />&bull; Childish Green eyes<br />&bull; Wavy, Shoulder-Length, Chestnut brown Hair,<br />&bull; Duck-Tail-Beard<br />&bull; Enthusiastic demeanor<br /><br />&bull; Quirk in Lip / Right<br />
<p>&nbsp;</p>
</section>
<hr /></section>
```

and the entry looks like this:
<img src="https://user-images.githubusercontent.com/79543184/145690221-048510ec-a355-4f19-ab30-060eb6a826ec.png" width="30%"/>

Now if you add a new chat entry to the log, you get the one instance at the top as is expected but also one instance after each `</section>`, which looks like this:
<img src="https://user-images.githubusercontent.com/79543184/145690092-b8b9c19e-cec5-4d28-8f94-4d93153e9295.png" width="30%" />

I'm guessing that your code looks for the end of a section and then adds an entry after that, but that a hard enter is obviously screwing that up by creating new `</section>` ends. And if so, I'm not sure how much you can really do about this. I'm guessing that's also a vast over-simplification as there is likely also code to add the newest entry to the top instead of the end. 

I'm not sure if it would make the solution easier if the "headings" were removed from the logs (such as "GM Only Adventure Log"). I'm thinking maybe there is code to re-insert that at the top after new entries are made. Maybe without it, the code becomes simpler and might have bearing on this issue. I'm shooting from the hip here however. 
My point though is that those headers really aren't needed. We're probably all naming these journal entries Adventure Log or DM Log or something similar so if it helps to remove, it is probably somewhat redundant. 

One work-around of course is to use `<Shift>+<Enter>` so that a new section isn't created. But in the heat of the game, I can see myself very easily screwing up and just hitting enter so hoping there's a more permanent solution possible.

Let me know if you have any questions or need more info/testing. Thanks @flamewave000.

**Comment by scooper4711** [comment]
Are you saying that if a user creates a log entry with /log command, then goes back and edits that chat message then it updates the message in the adventure log journal entry?

If so, I wonder how you are able to do this. I can't, and would very much want to.

**Comment by Shuggaloaf** [comment]
>Are you saying that if a user creates a log entry with /log command, then goes back and edits that chat message then it updates the message in the adventure log journal entry?

No, unfortunately, as that feature would be desired and preferable to what I'm doing now, which is to edit that AL entry. Which is what this issue has to do with, editing the AL.

**Comment by flamewave000** [comment]
yeah so it is not recommended to be editing the adventure log using the TinyMCE editor. It is better to edit the HTML directly because TinyMCE will do unexpected things with the HTML in the journal and will cause these kinds of issues. There's not really a way to prevent this since the journal is just raw HTML and I need to somehow know where to inject the messages.

@Shuggaloaf I like this idea, but it might be complicated to perform. I'd have to set the original message ID on each log entry, and then when ever a message is edited I would need to search the entire AL to find any logged entries with the same id and update them. Maybe make a feature request ticket and I can see if I can get something to work when I get around to working on v3.7

**Comment by Shuggaloaf** [comment]
Hey Flamewave000 bare with me if you already addressed this and it went over my head. 

My thought was that since the entire journal entry is only used for an adventure log, perhaps there is no need to have the code inject the `<section class="df-adventure-log">` and `</section>` any time the Enter key is pressed. You'd really only need to see that at the beginning and end of the journal entry. 

Or if that happens automatically, maybe there is a way that after the JE has been edited you can run through just the entire JE's text and remove either (1) all instances of those not at the 2nd or last line or (2) just delete all instances and then re-add them to lines 2 and last. 

That seems like it could make sure there is only 1 set and that they are always in the appropriate spot. 

(I'm sure I'm probably missing something though or not understanding how the coding works)

**Comment by flamewave000** [comment]
So the intent of the `<section>` tags is to allow a user to add content before or after the adventure log. Though I could look at maybe revamping the whole thing and customize the editor so that the journal entry only contains the AL and nothing else. If that's the case, it would be a pretty hefty chunk of work and would need an enhancement request ticket.
