### ISSUE TITLE
DF Chat Enhancements: Expansion of Recently Added Game World Time Feature

### ISSUE THREAD

**Issue by Shuggaloaf** [flamewave000/dragonflagon-fvtt#237]
In Issue #66 I (for some reason) was thinking that the request was to make the game world time appear in the actual chat window. I was also assuming that it would trickle down from there to both the Logs and the Archive. I just realized this feature was only added for the Logs.

Would it be possible to either:
1. Preferably, have it display in the chat window and also work in Logs and Archive; or
2. Minimally, add it to the Chat Archive as well?

Honestly the Chat Archive is what I'm most worried about, but I think the greater functionality overall would be point 1. For the Archive I find the current Foundry core method of displaying `x days, y hours... ago`  is pretty useless (no offense to you). 
When I'm looking back at the chat archive, pretty much 100% of the time what I'm looking for is what _game time_ did the players do such-and-such. Especially when you have sessions that may span several days. Knowing that the Fighter drank that nasty potion that has poisoned him for a week on the 10th of Fireseek at 6:32 pm (and the DM forgot to write that down ;-) ) is way more helpful than knowing he did so 7 days, 2 hours ago in real world time. Obviously this is just one (bad) example. 

Not sure if this would be too much trouble to add, but in my opinion it would really make the Chat Archive a lot easier to browse and find certain types of info.

**Comment by flamewave000** [comment]
Here's to hoping this works for you. It is not retroactive, so it will only work for new messages posted to the chat log as I have to fetch the SimpleCalendar timestamp and bind it as a flag to each message. This also means that if you disable the feature, the chat messages will show their normal times again.

![image](https://user-images.githubusercontent.com/3588046/171339090-6c178aea-fe0d-4cc5-861c-7d93796cee7f.png)

**Comment by flamewave000** [comment]
The default timestamp format is `'YYYY, MMM DD, HH:mm'` but I will have a setting that will allow you to customize it.

**Comment by Shuggaloaf** [comment]
Thanks flamewave! Yeah that looks great. I'm assuming this also carries over to the Chat Archive/Chat Log as well? And how does that work with the flags? I'd think the chat log is just copying that date/time's text so it should stay even if the module's disabled? Or am I off on that?

**Comment by flamewave000** [comment]
This will also work when displaying messages in the Chat Archives.

So messages actually keep a number timestamp and not a string. This makes sense as it is the best way to track times in the smallest form factor, while also not limiting how that time is used. As such, disabling the module will display the original functionality. SimpleCalendar must be used to create that formatted date and the game timestamp is saved in a flag in the message data, so Foundry won't display that secondary time without DFCE.

**Comment by Shuggaloaf** [comment]
OK that makes sense on how the date is stored. So as long as SC and DFCE are enabled I'm good to go. Got it. Thanks for the explanation.

One last question then I'll stop bugging you. although rare I know sometimes clearing flags is a thing. Are these flags separate from other game flags (world, scene, etc.) or if all flags are cleared then these flags will be as well?

**Comment by flamewave000** [comment]
So every Document has a field for flags. Chat Messages are their own document, so clearing flags on a scene does not clear them on chat messages as they're completely different documents. In order to clear flags on messages, a script would need to delete the flags on each individual chat message. But if you have a script does actually go through every single document in the database and deletes their flags, then yes it could potentially clear this one, but I doubt any flag clear script would do that.

**Comment by Shuggaloaf** [comment]
OK thanks for the explanation. Good to know how it works. I don't have any flag clearing scripts but I've seen mention of them so just wanted to know in case I ever needed to run one for some obscure reason. 

Thanks again for making this feature happen!
