### ISSUE TITLE
DF Scene Enhancement: Monk's Scene Navigation

### ISSUE THREAD

**Issue by BlackMoons** [flamewave000/dragonflagon-fvtt#239]
** Conflicting Module(s)**
Monk's Scene Navigation

**Describe the conflict**
Changing scenes via the scene list results in this warning:
libWrapper: Potential conflict detected between module DF Scene Enhancement and module Monk's Scene Navigation.
Module df-scene-enhance did not chain the wrapper for 'SceneDirectory.prototype._onClickEntityName'.

**Expected behavior**
No conflict warnings.

**Additional context (Optional)**
Not sure if this is actually an issue. Everything seems to work? but I thought I would report this warning regardless.

**Comment by flamewave000** [comment]
This is due to Monk adding an identical feature to his module that conflicts with DF Scene Enhancements. This is not something that can be corrected. Instead you can define the order of priority with libWrapper in-case you want the functionality of one module or the other to be used.

**Comment by BlackMoons** [comment]
Neat! thanks for the clarification.

**Comment by flamewave000** [comment]
I'm not sure why AT would be overriding the `SceneDirectory`'s `_onClickDocumentName` function. I'm unfamiliar with that module so I'm don't know what exactly the feature would be that is using it. That function is only invoked when you click on a scene in the sidebar.
