### ISSUE TITLE
DF Manual Rolls: Disabled for all exept Owned by Player

### ISSUE THREAD

**Issue by Battenhatch** [flamewave000/dragonflagon-fvtt#240]
This may be a bit of an outlier, but would matter to me in the type of game I run. The game in question has me, the DM, running the only computer used. I thus input all the values that the players roll around the table, and no players are logged in during the session. AFAICT this means that I have to have manual rolls enabled for the NPC's also (as it's all DM controlled thins or none at my end). I'd like to be able to tollge the module so that Manual ROlls is only called if the token rolling is owned by a player role, even if the player is not logged in. Saving that one click pr. operation would actually matter (to me at least ;-) )

If you can do this already and I'm just not seeing it, I'll be a happy man :-)

**Comment by flamewave000** [comment]
So current solution is to just close the window and it will perform the random rolls. Our you can change the settings to Toggle and you will have a single toggle button to toggle manual rolls on or off before making rolls.

Unfortunately rolls do not provide any information as to their source, and to do so would require adding patches for each and every System as they all do things differently.
