### ISSUE TITLE
DF Curvy Walls: Template is not drawing on canvas, and error reported

### ISSUE THREAD

**Issue by flamewave000** [flamewave000/dragonflagon-fvtt#260]
Placing the curve tool onto the scene is not drawn and errors appear in the console.

![image](https://user-images.githubusercontent.com/3588046/147611395-5fb7ad12-a4f7-4833-896c-db6a22158752.png)

**Comment by Tukurai** [comment]
I've noticed this issue. This module has been one of my favorite tools for the past months. I hope you manage to find the issue.

**Comment by flamewave000** [comment]
@Tukurai This is an issue caused by the new Foundry v9 update, so it's just par for the course when migrating that something is going to be broken due to API changes by Foundry.
