### ISSUE TITLE
DF Curvy Walls 3.3.0 not published

### ISSUE THREAD

**Issue by crimsonknave** [flamewave000/dragonflagon-fvtt#276]
According to https://foundryvtt.com/packages/df-curvy-walls `3.2.4` is the latest, but https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-curvy-walls/CHANGELOG.md shows 3.3.0 is the latest and supports foundry v9. I'm guessing something happened and it didn't get published like the others?

**Comment by flamewave000** [comment]
It is currently in pre-release for my patrons. This is a 1 week beta. It will be fully released at the end of this week. This is the same for Chat Enhancements, Scene Enhancements, and Architect.
