### ISSUE TITLE
DF Active Lights: Not working in v9

### ISSUE THREAD

**Issue by dev7355608** [flamewave000/dragonflagon-fvtt#278]
Light animation isn't working properly in v9.  `animData` is still in the v8 format. Most light-specific properties have been moved to `data.config` from `data`:
```
data.dim -> data.config.dim
data.bright -> data.config.bright
data.angle -> data.config.angle
data.tintAlpha -> data.config.alpha
data.tintColor -> data.config.color
```
`data.rotation` is still `data.rotation`.

Another thing I noticed: Why isn't the normal `updateSource` called? This bypasses other modules that wrap `updateSource`. I recommend to remove `_updateSource` and replace `LightAnimator._updateSource.bind(light)();` by `light.updateSource()`, which schedules lighting/sight refreshes, and then we don't need to do it in `_LightingLayer_animateSource`, where lighting/sight refreshes are permanently spammed even if no DF animated lights are in the scene, which impacts the performance significantly.

**Comment by flamewave000** [comment]
DF Active Lights has already been updated for V9 compatibility, this particular issue is covered by #267.

As for the question about using the core `updateSource` function, the problem is this bit of code here:
![image](https://user-images.githubusercontent.com/3588046/147974056-86985ed9-4506-4aea-aa20-23e8abccc681.png)
If the light radius drops to 0 at any given point, the light be automatically deleted from the lighting layer by Foundry. This is obviously not great if anyone is  attempting to create a pulsing light. Unfortunately that cannot be correct by a simple wrapper, but must be overridden entirely, so I decided to create my own function that had less code and improved performance.

**Comment by dev7355608** [comment]
It's definitely not working (v1.2.0). Video:

https://user-images.githubusercontent.com/31905376/147977458-8c05228f-4e61-4a7a-a070-67285b839026.mp4

And look at those uniforms: see `exposure` is -0.5, `colorBright` is black, etc.
![image](https://user-images.githubusercontent.com/31905376/147977527-efeba3f7-18b2-41a7-9608-f99da938c57d.png)

> If the light radius drops to 0 at any given point, the light be automatically deleted from the lighting layer by Foundry. This is obviously not great if anyone is attempting to create a pulsing light. Unfortunately that cannot be correct by a simple wrapper, but must be overridden entirely, so I decided to create my own function that had less code and improved performance.

That shouldn't be an issue, right? It would be added right back to the sources of the lighting layer once the radius is greater than zero. You could also simply add something like `Math.max(bright, 0.001)` / `Math.max(dim, 0.001)` to your `animData` if deletion is undesirable.

What is important though is that `_LightingLayer_animateSource` must not request lighting/sight updates unless it is strictly required. Even if no DF animated lights are in the scene, lighting and sight are constantly refreshed.
https://github.com/flamewave000/dragonflagon-fvtt/blob/68eb4dbae5a7db28a5ebf136891cfda830a00ccf/df-active-lights/src/LightAnimator.ts#L60-L67

**Comment by flamewave000** [comment]
I'm not sure why your light is not working, it is working in my test V9 environment. Maybe a module conflict?

I ran into an issue where if a light was deleted from the lighting layer, it had to receive an actual data "update" in order for the LightingLayer to re-add it to the canvas. Simply calling the updateSource does not re-add it to the Canvas. Though, I could look at adding a "buffer zone" where the light radius snaps to to prevent `== 0` failure.

As for the the concern of too many updates, the module only animates and updates each light IF there is an animated light source in the scene. This is checked for at [df-active-lights/src/LightAnimator.ts:75](https://github.com/flamewave000/dragonflagon-fvtt/blob/68eb4dbae5a7db28a5ebf136891cfda830a00ccf/df-active-lights/src/LightAnimator.ts#L75). If there is no anim data, or the anim data is empty, it is ignored and the function immediately returns for that light. But I do see what you mean that for each render frame, the sight layer is scheduled for a refresh. I can add boolean return on each `_PointSource_animate` to say if the light animated or not and prevent a sight layer update if no animation occurred.

**Comment by dev7355608** [comment]
I double checked: no other are modules active. I uninstalled/reinstalled Active Light, CTRL+F5 and devtools disabled cache, new scene, new light. Same results.

> I ran into an issue where if a light was deleted from the lighting layer, it had to receive an actual data "update" in order for the LightingLayer to re-add it to the canvas.

Hm, that's definitely odd.

> I can add boolean return on each _PointSource_animate to say if the light animated or not and prevent a sight layer update if no animation occurred.

That would be great.

**Comment by flamewave000** [comment]
> Hm, that's definitely odd.
Yeah it was very frustrating that there wasn't a simpler method to re-add the light to the CanvasLayer. But that might be moot if I do the min/max buffer 🤷🏽‍♂️

**Comment by irbian** [comment]
![image](https://user-images.githubusercontent.com/3071767/148079431-b21b90cb-69e4-4ca3-a9df-9b3557205e81.png)

the sounds folder disappeared on the zip?

**Comment by irbian** [comment]
![image](https://user-images.githubusercontent.com/3071767/148079716-4358db85-4996-4c70-853f-b43a629117c5.png)

my module folder after updating today

**Comment by flamewave000** [comment]
@irbian you're issue is unrelated to this ticket. Please open a separate ticket for DF User Logger.
