### ISSUE TITLE
DF Curvy Walls: latest version references "lib-df-hotkeys" as a dependency

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#282]
**Module**
DF Curvy Walls 3.2.4 still references "lib-df-hotkeys" as a dependency

**Comment by flamewave000** [comment]
DF Curvy Walls v3.2.4 only supports FoundryVTT 0.8.x and therefore needs the Hotkeys library to function. Please wait for v3.3.0 to release for FVTTv9 support.
