### ISSUE TITLE
DF Various: Updates to latest version not being offered by foundry

### ISSUE THREAD

**Issue by cs96and** [flamewave000/dragonflagon-fvtt#288]
**Module**
Module Name and Version: DF Chat Enhancements 3.51, DF Curvy Walls 3.2.4

**Describe the issue**
I have the above versions of the those modules installed, and Foundry is telling me they are up to date.  However I can see that newer versions have been released from their changelogs.  I have tried uninstalling and reinstalling them, but it always installs the older version.

There may be other of your modules suffering from the same problem, but those are the two I have installed (and DF Settings Clarity, but that has not been updated in a while and foundry is giving me the latest version).

**To Reproduce**
1. Go to foundry module installation page
2. Install DF Chat Enhancements and DF Curvy Walls
3. See that the above versions are installed, when newer ones are supposedly available.
4. Try to update the modules.  No updates are offered.

**Expected behavior**
Newer versions should be installed.

**Comment by flamewave000** [comment]
These modules are in Patron-only Pre-Release and not currently available to public. I am planning to publicly release them tomorrow (Saturday, January 8).

**Comment by cs96and** [comment]
Ah, OK thanks!
