### ISSUE TITLE
DF Quality of Life: Perform auto-targeting for gridless scenes

### ISSUE THREAD

**Issue by Lifthraser** [flamewave000/dragonflagon-fvtt#291]
**Module**
DF quality of life version 1.7.1
No other module active
Foundryvtt: Version 9 - Build 242

**Describe the issue**
Targeting within a template only works with square and hexa scenes, not gridless.

**Comment by flamewave000** [comment]
I don't typically use gridless for anything, so it wasn't really a consideration when I built the auto-targeting feature. I can look into including it.

**Comment by Lifthraser** [comment]
Still waiting for this awesome feature, finger crossed :D
