### ISSUE TITLE
DF Curvy Walls: Left sidebar can get overlapped

### ISSUE THREAD

**Issue by Squishiest-Grape** [flamewave000/dragonflagon-fvtt#296]
**Module**
DF Curvy Walls v3.30

**Describe the issue**
The added wall control side buttons do not seem to be added to the main list of buttons.  This causes problems when the buttons for the wall controls begin to wrap around, they overlap/are overlapped by the curvy wall buttons.  In addition, when the sidebar gets repositioned, with say Minimal UI, the buttons do not scale with the other buttons and get a weird vertical offset.  

![image](https://user-images.githubusercontent.com/48263319/148674718-e63a28cd-72fc-4a52-97a2-c94925a2420a.png)
![image](https://user-images.githubusercontent.com/48263319/148674777-00850a6b-4e2e-44b8-b1eb-1785fce5247f.png)

Foundry 9.242  DnD5e

**Comment by flamewave000** [comment]
The wrapping issue sounds like a regression I'll have to correct.

Aside from that, I don't do support for UI overhaul modules, since they're all heavily customized CSS. It is up to the module author to add CSS to adjust my UI.

**Comment by kgruszcz** [comment]
That is perfectly reasonable not supporting the UI overhaul mods.
I was mainly mentioning it because I thought the issues were related as the additional buttons from DF Architect get properly resized by Minimal UI.

**Comment by irbian** [comment]
![image](https://user-images.githubusercontent.com/3071767/163651656-1b61804a-24f1-47ae-9955-7ca3611784f8.png)

I don´t see the curved wall buttons with that version of architect 3.2.2 enabled

**Comment by flamewave000** [comment]
@irbian curvy walls now requires Library: DF Module Buttons to be enabled.

**Comment by irbian** [comment]
dont know why didnt work with  Library: DF Module Buttons  installed before but it does now, thanks!
