### ISSUE TITLE
DF Chat Enhancements: Module Credits

### ISSUE THREAD

**Issue by Weissrolf** [flamewave000/dragonflagon-fvtt#298]
**Conflicting Module(s)**
- Module Credits

**Describe the conflict**
"TypeError: An error occurred while rendering ModuleCreditsDialog 140: marked is not a function
[Detected 1 package: module-credits]"
Part of the functionality of Module Credits gets broken, like clicking the button for Info and Changes in the "Manage Modules" window (which is changed by Module Credits).

**Expected behavior**
No errors of Module Credits, which seems to work once DF Chat Enhancements is disabled.

**Comment by mouse0270** [comment]
Resolved in version 0.0.4.0 (I don't fully understand ES Modules, but if I understand them correctly, this should no longer cause a conflict.) We can discuss how to better support this common library going forward if you like. But at least for now this should be resolved with the latest release of Module Credits
