### ISSUE TITLE
DF Chat Enhancement:: Breaking Chat Message Border

### ISSUE THREAD

**Issue by Ghostdesu** [flamewave000/dragonflagon-fvtt#299]
**Module**
 DF Chat Enhancements v3.6.0

**Describe the issue**
Colored message border in chat is only displayed to the user, others' messages have default color border.

**To Reproduce**
1. Enable DF Chat Enhancements and prerequisites
2. Have User1 send a message in chat
3. Observe the issue as User2

**Expected behavior**
All messages should have colored border according to the player that sent them.

**Screenshots (Optional)**
Gamemaster POV
![image](https://user-images.githubusercontent.com/31375910/149593660-f6130b16-41df-494c-a81d-fc7dfb8e2300.png)

Player 1 POV
![image](https://user-images.githubusercontent.com/31375910/149593673-487a78bf-d4e1-4bd7-b27c-098b64f3674e.png)

Seemingly nothing of note in console
![image](https://user-images.githubusercontent.com/31375910/149593711-464df655-83f3-4354-8f13-3733e059ae01.png)

**Comment by flamewave000** [comment]
So this is actually the default behaviour for FoundryVTT. I could certainly see if I can change this as a feature though via a module setting.

**Comment by Ghostdesu** [comment]
Creating a new world with no modules does show the player border appropriately though.

![image](https://user-images.githubusercontent.com/31375910/171037258-9f947ee2-e3c0-465d-bbee-f2702226851e.png)
(Gamemaster POV)

![image](https://user-images.githubusercontent.com/31375910/171037279-1138a931-b241-4740-be62-23c638c1cd6e.png)
(Player 2 POV)
