### ISSUE TITLE
Module Prevents DD Import from working

### ISSUE THREAD

**Issue by justinthejaguar** [flamewave000/dragonflagon-fvtt#3]
In version 7.3, this module prevents the user from uploading using the DungeonDraft Import module. https://foundryvtt.com/packages/dd-import/.

User receives this error in the console log.
![](https://user-images.githubusercontent.com/38022481/95596450-6633d600-0a1b-11eb-8a1d-582a7cd312b8.png)

I notified Moo Man in this issue as well:
https://github.com/moo-man/FVTT-DD-Import/issues/42

My current workaround is just disabling DF Scene Enhancement until I am done with map uploads and re-enabling during the game.

**Comment by flamewave000** [comment]
I haven't had a chance to test my modules on 0.7.X yet, so thank you for letting me know. I do plan on getting them updated as soon as I have some free time. I'm happy you have a work-around for the time being.

**Comment by justinthejaguar** [comment]
Side note. It is a much welcomed module for me and my players. Thanks for keeping the game looking clean.

Thank you,

Justin Payton
justinthejaguar@gmail.com

**Comment by flamewave000** [comment]
@justinthejaguar Could you retry this issue using v2.0? I have corrected the thumbnail creation code for 0.7.4+.

**Comment by justinthejaguar** [comment]
Tested. Fixed.
