### ISSUE TITLE
DF Chat Enhancement: Chat Merge incompatible with Pathfinder 2e system attack rolls

### ISSUE THREAD

**Issue by Ghostdesu** [flamewave000/dragonflagon-fvtt#300]
**Module**
 DF Chat Enhancements v3.6.0

**Describe the issue**
Merged attack rolls overlap the tags when using Chat Merge feature of Chat Enhancements. (other rolls appear unaffected)

**To Reproduce**
1. Enable DF Chat Enhancements and prerequisites.
2. Create a Player Character actor.
3. Roll the preconfigured unarmed attack twice.
4. Observe issue in chat.

**Expected behavior**
The roll should not overlap the text above it.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/31375910/150648771-c705fbec-d746-40d5-b4e8-19d94cdbdea3.png)
![image](https://user-images.githubusercontent.com/31375910/150648881-b7e85b1e-8a2b-4320-8d34-1b19c9d7f3a4.png)
![image](https://user-images.githubusercontent.com/31375910/150648939-d1784ada-c4c3-4514-9f2f-46d8e6773ed4.png)
![image](https://user-images.githubusercontent.com/31375910/150648773-4be6c35f-2c14-47b3-8a68-351fd9d41f83.png)

**Comment by flamewave000** [comment]
I'm not able to reproduce this issue. It is possible that PF2e has changed their styling and this may no longer be an issue.
![image](https://user-images.githubusercontent.com/3588046/171044350-9180d283-3f83-4232-a24c-7dfc731040ad.png)
