### ISSUE TITLE
DF Curvy Walls: Bug - Inability to Angle Walls

### ISSUE THREAD

**Issue by FroggMaster** [flamewave000/dragonflagon-fvtt#303]
**Module**
Module Name and Version (DF Curvy Walls v3.3.0)

**Describe the issue**
When creating a curved wall, if you accidentally click on the point for another wall you are no longer presented with the options to manipulate the curve of the wall. 

**To Reproduce**
1. Create a curved wall as normal. 
2. Create a second curved wall, but before angling or clicking confirm, click on the point of any other existing wall, and move that point. 
3. The curved wall you were placing disappears, but the confirmation dialog remains. 
4. The next wall you go to place, will no longer have the options to curved any walls.  Though the will still get created with curve, you can no longer change the angle. 

**Expected behavior**
Upon creation of the next curved wall, the angling ability should not vanish. 
Perhaps it would be best to disable the movement of other wall points during creating a curved wall. 

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/12762784/150878186-70848bcc-adcd-4386-9dd7-dcd1501a9207.png)
![image](https://user-images.githubusercontent.com/12762784/150878218-b97c9466-7a78-49f6-a624-4221e719368c.png)

**Comment by GabrielOsvair** [comment]
The module has been idle for a long time, has it been discontinued?

**Comment by flamewave000** [comment]
No I just haven't had time to work on things since the V9 update due to life stuff. I'm still trying to stay active on the GitHub and in Discord though.

**Comment by GabrielOsvair** [comment]
I understand, wish you luck. Your modules are amazing!
