### ISSUE TITLE
DF Module Name: lib-df-hotkeys

### ISSUE THREAD

**Issue by pmoore603** [flamewave000/dragonflagon-fvtt#304]
**Module**
version 2.3.5

**Describe the issue**
Only active module is lib-df-hotkeys
Configuration option does show up, but S hotkey doesn't work, nor is there a way to add hotkeys.
Fails to load in latest Foundry (version 9, build 242):
foundry.js:51468 Uncaught TypeError: Cannot read properties of undefined (reading 'toggle')
    at SceneControls._onClickTool (foundry.js:51468)
    at Object.onKeyDown (lib-df-hotkeys.js:9)
    at Function._handleKeyDown (lib-df-hotkeys.js:5)

**To Reproduce**
1. Install the module and enable it.
2. Open developer tools and you can see the exception.

**Expected behavior**
It should load and run properly.

**Screenshots (Optional)**
n/a

**Comment by flamewave000** [comment]
Because FoundryVTT V9 has an official keybindings system, this module is now obsolete. It is being kept alive only for those still on 0.8.9, but will no longer receive any updates.
