### ISSUE TITLE
DF Settings Clarity: console warnings about Unknown restriction/scope on registered setting with some modules

### ISSUE THREAD

**Issue by itamarcu** [flamewave000/dragonflagon-fvtt#305]
**Module**
DF Settings Clarity v3.2.1

**Describe the issue**
When launching a world and looking in the developer console, I see some warnings:

![image](https://user-images.githubusercontent.com/6516621/151550685-b89a7ad8-455b-4bf6-9bfe-66b9bc773280.png)

```js
df-settings-clarity.js:3 Unknown restriction/scope on registered setting for drag-ruler.settings.speedProviderSettings.name". Defaulting to "client"
formatName @ df-settings-clarity.js:3
patchGameSettingsMenus @ df-settings-clarity.js:3
(anonymous) @ df-settings-clarity.js:3
_call @ foundry.js:294
callAll @ foundry.js:253
setupGame @ foundry.js:5525
_initializeGameView @ foundry.js:6498
_initializeView @ foundry.js:6474
initialize @ foundry.js:5430
await in initialize (async)
🎁call_wrapped @ libWrapper-wrapper.js:510
🎁libWrapperInit @ libWrapper-api.js:778
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:186
window.addEventListener.once @ foundry.js:62429
```

(+3 more, almost identical)

In this case this is due to the following settings windows:
- [Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler) - speed provider settings
- [Quick Insert](https://gitlab.com/fvtt-modules-lab/quick-insert) - indexing and filter settings
- Web RTC - I'm pretty sure this is the core Foundry Audio/Video Configuration menu

What should be done to remove these warnings?

**Comment by flamewave000** [comment]
So this would require those modules to update their code to provide proper scope/restriction flags when registering their settings and menus. Otherwise, you'll just have to live with the warnings. It just means DFSC cannot determine if it is a World settings or a Client setting.

**Comment by itamarcu** [comment]
@flamewave000 what about Web RTC (core Foundry)?

**Comment by manuelVo** [comment]
Unfortunately providing a scope flag for Drag Ruler's menu isn't possible, since the menu contains mixed settings. Some of them are world scope, some of them are client scope.

Maybe we could intoduce some flag that drag ruler could set to convey that fact to DF Settings Clarity?

**Comment by itamarcu** [comment]
I'd rather have it be resolved because as a fellow module developer I look at the console constantly and pay extra attention to errors and warnings that pop up;  and with my current ~70 installed modules, I only get 5 warnings, 4 of which are due to this issue.  If I could get the amount down to 0, I'd be very happy :]
