### ISSUE TITLE
DF Quality of Life: Advanced Spell Effects

### ISSUE THREAD

**Issue by MorganVergara** [flamewave000/dragonflagon-fvtt#306]
**Conflicting Module(s)**
Advanced Spell Effects

**Describe the conflict**
The following error message shows when I startup my world.

![image](https://user-images.githubusercontent.com/30846057/151726539-f37265b7-9c0e-4cf3-97f1-d1b1147d8ecd.png)

The console shows:

![image](https://user-images.githubusercontent.com/30846057/151726564-b4882ea4-46b6-4dae-ad8d-988ff2990e3c.png)

**Expected behavior**
No conflict error message should appear.

**Screenshots (Optional)**

**Additional context (Optional)**
Foundry 9.245
D&D 5E 1.5.7

The following modules were active:

![image](https://user-images.githubusercontent.com/30846057/151726839-57552e30-a2c9-4fc6-a6ac-224d8b878086.png)

This happened just this evening. This afternoon, all was working well, so it's a recent change.

From the error message, it looks like the problem is with ASE, but I'm not the best judge of that, so I thought I'd let you know as well.  Thanks!

Morgan

**Comment by flamewave000** [comment]
I just looked into Advanced Spell Effects and it appears to be that they have changed their Override to a Wrapper for the template highlight.

I'm going to close this ticket, but let me know if you still have any issues.
