### ISSUE TITLE
DF Manual Rolls: Conflicts with Monk's Little Details

### ISSUE THREAD

**Issue by flamewave000** [flamewave000/dragonflagon-fvtt#307]
Per Vestium's report: Monk's Little Details is performing some kind of roll at the start of each round of combat which is causing an error to occur within DF Manual Rolls.
![image](https://user-images.githubusercontent.com/3588046/151743018-9dc2f2bd-867e-4d2e-9742-20f6e392c6d1.png)

**Comment by UnoriginalDM** [comment]
I believe this is the "Round Start", "Round End" that Monk's Little Detail does.
