### ISSUE TITLE
DF Chat Enhancements: Dice so Nice scroll to bottom

### ISSUE THREAD

**Issue by JiDW** [flamewave000/dragonflagon-fvtt#308]
** Conflicting Module(s)**
- Dice So Nice!

**Describe the conflict**
As reported by our user here: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/297
DsN has its own scrollToBottom when a roll end.

**Expected behavior**
DsN respects the DF Chat Enhancements setting

**Additional context (Optional)**
Hey, DsN dev here. As reported by this user, our modules conflict as DsN needs to use `window.ui.chat.scrollBottom` at the end of a 3D roll.
How can we proceed from there? Is this something you can fix directly in your code (without wrapping DsN function) or if not, can you tell me which setting I should check for before I use scrollToBottom?

Thanks!

**Comment by flamewave000** [comment]
Sorry I haven't gotten back to you on this. So I don't currently override that function, I instead just override the `postOne` function. I think the simplest solution would be for me to override the `scrollBottom` function and make it NoOp when my scrolling button is enabled.

**Comment by JiDW** [comment]
OK great! Thanks!
