### ISSUE TITLE
DF Settings Clarity: Search is searching very illogically

### ISSUE THREAD

**Issue by dmrickey** [flamewave000/dragonflagon-fvtt#309]
**Module**
DF Settings Clarity 3.2.1

**Describe the issue**
I think the image best describes it, the search appears to be splitting up the input however it likes and matching the chars in order on anything within the setting and/or description. It's basically like it's doing a `.*` regex between every character input.

**To Reproduce**
1. Go to settings and search

**Expected behavior**
Don't split the search term where there isn't a logical break

![image](https://user-images.githubusercontent.com/3664822/152630754-639ef695-7215-437e-9783-6cb71aedc2be.png)

**Comment by flamewave000** [comment]
So this isn't really something I can prevent as I am using a third-party Fuzzy Search library. The closest solution would be what is proposed in this ticket #178

**Comment by dmrickey** [comment]
Does the fuzzy search not return a score to indicate how likely of a match it is? I'd expect those results above to have a pretty low score
