### ISSUE TITLE
Pause can't be toggled

### ISSUE THREAD

**Issue by MS-PBS** [flamewave000/dragonflagon-fvtt#31]
Foundry ver. 0.7.9
System: DnD 1.2.4
DF curvy walls ver.: 1.1.0
Other modules active: No

I got this issue this morning and using Find the Culprit, I figured out the module making me unable to unpause the game is DF Curved Walls. I have tested it in my test world with only this module active and I can reproduce it, so it's unlikely to be a conflict with other modules.

When the module is active, pause state can't be changed. The pause icon gets refreshed, but nothing else changes. If the game was not paused to begin with (I unpaused it by deactivating the module, unpausing the game and enabling the module again), nothing seems to happen at all. 

Calendar/weather provides a console message whenever the game is paused/unpaused. Enabling it, I could see that, when DF Curved Wall Creator is active and I attempt to toggle the pause state, instead of getting one message I get two. 

For example, if the game is paused, I get "Game Paused: false" and then immediately below, "Game Paused: true". The opposite is also true for when the game is unpaused. So I guess your module calls the pause toggle again when a GM calls it and thus there is a net zero change.

**Comment by MrVauxs** [comment]
Another user here, same issue. Upon removing the module the issue stopped.

**Comment by Voldemalort** [comment]
Same issue here. If you watch console it actually toggles pause twice.

**Comment by flamewave000** [comment]
This must be caused by the latest versions new keyboard binding to get the enter and delete keys. Super weird that it is causing this. I'll look into it ASAP and get an update out with a fix. In the meantime, you can uninstall the module and install the v1.0 using this url in the install module window:

https://github.com/flamewave000/dragonflagon-fvtt/releases/download/df-curvy-walls_1.0.0/module.json

**Comment by flamewave000** [comment]
I've found the issue. Was in a bit of code I actually was no longer using and forgot to remove 🤦‍♂️
I'll have a fix out as v1.1.1
