### ISSUE TITLE
DF Settings Clarity: Settings search completely mangles the setting description

### ISSUE THREAD

**Issue by dmrickey** [flamewave000/dragonflagon-fvtt#310]
**Module**
DF Curvy Walls 3.2.1

**Describe the issue**
After searching, all of the descriptions for an individual mod are concatenated and repeated on every setting in that mod

**To Reproduce**
1. Go to "Module Settings"
2. Search
3. Clear search

**Expected behavior**
I expect the descriptions to remain as they were before the search and not like the image

**Screenshots (Optional)**
If applicable, add screenshots to help explain your problem. If you hit the [F12] key while in Foundry, you will see a window appear. Open the "Console" tab (if it's not already open). If you scroll through this, it is a log for the page. Anything that appears in RED are errors. You can screenshot those errors and add them to this ticket.

good:
![image](https://user-images.githubusercontent.com/3664822/152630925-a4bdad7d-5354-4cf4-96aa-6f4c2ef1f266.png)

bad:
![image](https://user-images.githubusercontent.com/3664822/152630919-7bca8e4c-ee7b-44a0-99b1-d96b305d4672.png)

**Comment by flamewave000** [comment]
So this is not a bug in DF Settings Clarity. This looks more like a conflict with some other kind of module you are using that is changing your module settings UI. I currently only support Core FoundryVTT and [Tidy UI - Game Settings](https://foundryvtt.com/packages/tidy-ui_game-settings).

**Comment by dmrickey** [comment]
Copied from my closed issue: 

> Does the fuzzy search not return a score to indicate how likely of a match it is? I'd expect those results above to have a pretty low score.
> 
> I just clicked through to the issue you linked, to the referenced package and it looks like it does return a score, so if it does return sane values, only showing results with a minimum score of "_something_" might be a good option
