### ISSUE TITLE
DF Chat Enhancements: PF2e Dorako UI

### ISSUE THREAD

**Issue by MrVauxs** [flamewave000/dragonflagon-fvtt#313]
**Conflicting Module(s)**
- [PF2e Dorako UI](https://github.com/Dorako/pf2e-dorako-ui)

**Describe the conflict**
CSS trickery abound. See the below image.
![image](https://user-images.githubusercontent.com/32039708/152980949-72ddb961-f683-43e4-876c-77d281c14873.png)

**Expected behavior**
Dorako UI has it's own chat formatting. It should look like below.
![image](https://user-images.githubusercontent.com/32039708/152981052-584ab64e-5914-4444-8058-5912c1a7a215.png)

**Additional context (Optional)**
Already reported on Dorako's GitHub, but thought both modules should look into it.
**[Issue in question.](https://github.com/Dorako/pf2e-dorako-ui/issues/18)**

**Comment by flamewave000** [comment]
So if you're looking to have the Dorako UI styling, you can disable the chat styling options in the DFCE module settings. I don't provide support for UI overhaul mods, only the core FoundryVTT and I try to prevent code conflicts with other modules via `libWrapper` and careful code design.
