### ISSUE TITLE
DF Chat Enhancement: Conflict with Ready Set Go!

### ISSUE THREAD

**Issue by Baxmann** [flamewave000/dragonflagon-fvtt#315]
**Describe the conflict**
The Hourglass button added by Ready Set Go gets pushed up due to not having enough space.

**Expected behavior**
The Hourglass to be In Line with the other buttons.

**Screenshot**
![image](https://user-images.githubusercontent.com/34702584/154335974-72a609b0-64c9-4ea7-b24f-1f9421ad8944.png)

**Possible Solution**
I have a suggestion to the solution, where you add the option to remove the .chat-control-icon, which doesn't seem to do anything. I advise making it an option, as some module or system out there might use it. You might have a different solution, but that was the easiest way I thought of solving the problem.

**Comment by flamewave000** [comment]
So I cannot remove that icon as it is used by [Dice Tray](https://foundryvtt.com/packages/dice-calculator) as well as potentially other modules. I suggest you enable the setting "Chat Archive: Hide the Export Chat Log button" to make more room.

![image](https://user-images.githubusercontent.com/3588046/154364212-ce841786-9de1-4c08-823a-99d1fd8a2812.png)
