### ISSUE TITLE
DF Chat Enhancement: Console Error

### ISSUE THREAD

**Issue by SR5060** [flamewave000/dragonflagon-fvtt#318]
**Module**
DF Chat Enhancement

**Describe the issue**
![image](https://user-images.githubusercontent.com/85184490/155769461-d0ca6b9c-d7b8-4818-8a85-a425327e9091.png)

**To Reproduce**
not clear what causes it at this point

**Expected behavior**

**Screenshots (Optional)**
If applicable, add screenshots to help explain your problem. If you hit the [F12] key while in Foundry, you will see a window appear. Open the "Console" tab (if it's not already open). If you scroll through this, it is a log for the page. Anything that appears in RED are errors. You can screenshot those errors and add them to this ticket.

**Comment by flamewave000** [comment]
Might relate to #231

**Comment by flamewave000** [comment]
Duplicate of #231
