### ISSUE TITLE
Toolbar Controls to Edit a Newly-Created Curve are not Functional in the Foundry Application

### ISSUE THREAD

**Issue by kamatikos** [flamewave000/dragonflagon-fvtt#32]
I have attempted to reproduce this bug in the Foundry application (version 0.7.9) for Linux as well as a Chromium-based browser (on Linux). In reproducing the bug, I created a new world with the D&D 5E system and made sure that all other modules were disabled. The bug *only* appears in the Foundry application, and everything seems to be working properly when done in the Chromium browser.

____

After beginning the creation of a new section of wall (IE: selecting the wall type and curve type, then clicking and dragging on the canvas to shape the wall), the buttons on the additional toolbar menu that pops up (below) don't do anything. The keyboard controls *do* work, and this issue existed prior to the recent keyboard bug-fixes (prior to version 1.1.1).

![Toolbar](https://user-images.githubusercontent.com/3813675/105613377-1d1c4d80-5d90-11eb-9a98-4d21321e27a9.png)

- The `+` and `-` buttons do not alter the number of wall segments in the curve.
- The `✓` button does not submit / finalize the curve.
- The `×` button does not erase / destroy the curve.
- The `🔒` button does not toggle the coupling.

There are two errors which seem only to appear upon loading into a world / refreshing the page. *However*, these errors appear in both the Foundry application and the Chromium browser.
```
TypeError: Cannot read property 'preview' of undefined
    at BezierControl.injectControls (BezierControl.js:130)
    at df-wall-curves.js:19
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at SceneControls._getControlButtons (foundry.js:20318)
    at new SceneControls (foundry.js:19771)
    at Game.initializeUI (foundry.js:6634)
    at Game.setupGame (foundry.js:6545)
    at async Game._initializeGameView (foundry.js:7319)
    at async Game.initialize (foundry.js:6471)
```
```
TypeError: Cannot read property 'preview' of undefined
    at BezierControl.injectControls (BezierControl.js:130)
    at df-wall-curves.js:19
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at SceneControls._getControlButtons (foundry.js:20318)
    at SceneControls.initialize (foundry.js:19858)
    at TokenLayer.activate (foundry.js:11107)
    at TokenLayer.activate (foundry.js:12228)
    at TokenLayer.activate (foundry.js:40283)
    at Canvas._initializeCanvasLayer (foundry.js:10341)
```

**Comment by flamewave000** [comment]
The two stack traces you posted are known but unrelated (from a call I'm no longer making).

As for this issue, I've heard from one other user they are having the same issue, but I'm unable to reproduce it on Foundry 0.7.9 in either Chrome or the Foundry App (windows). It is most likely a conflict with a module that I don't have, but you say you've tried it with no other modules enabled?

**Comment by kamatikos** [comment]
Correct. All other modules disabled.

**Comment by flamewave000** [comment]
I still cannot find any way to reproduce this issue. I've tried it on several browsers (Edge, Chrome, Firefox, Brave) and from a Linux Server (my self-run hosting) as well as from the FoundryVTT app. The buttons are always working for me. I'm not sure what else I can try to get this issue to reproduce.

**Comment by kamatikos** [comment]
Oh well. Don't lose sleep over it. The module is of such a nature that it's mostly useful for map preparations, which don't happen during games. Switching to a browser to lay down walls with the module will still be better than not using the module.

**Comment by flamewave000** [comment]
I may have some time today to set up a ubuntu vm on my hyper visor and try running the application for Linux. It could be an issue with that specific build of foundry. It's the last thing I can think of that is different between what we're doing, since it works fine in the browser 🤷‍♂️

**Comment by slicknickicarus** [comment]
I am indeed having the same issues, but the same workaround functions for me. I'm getting no errors in the debug, and replicated the error with no modules. 

Also, like above, not a big deal to pop into the browser, but interesting to note.

**Comment by flamewave000** [comment]
@slicknickicarus Are you also running the foundry desktop app on linux?

**Comment by slicknickicarus** [comment]
@flamewave000 Bah, sorry, critical missing info. 

No, I'm running Windows, through the Foundry App, and the workaround through Chrome.

**Comment by Hebelios** [comment]
I am running windows and am experiencing the same thing.
I can however press enter to apply the wall.

Curious. Never had the module installed before, so no remnants from earlier versions and no modules installed either.

**Comment by DFreds** [comment]
I am also experiencing this issue with no other modules enabled. None of the buttons work in the Foundry application

Win10, running the Foundry-App 0.7.9 with 5e 1.2.4, version 1.2.1 of Curvy Walls

**Comment by flamewave000** [comment]
Ok so the current workaround is using a browser, though the Enter and Delete keys are still working for the Apply/Clear functions. As such, I still have no idea how to essentially "break" my Foundry and may need someone to volunteer some time to help me out with this. I would need someone to let me remote into their computer (maybe with TeamViewer so it would be safe and secure) to see and test the issue. If anyone would like to help me out with that, please feel free to message me on Discord and we can set up a time for it. I am in EST, and available any time after 6:30 on weekdays.
Discord: flamewave000#6766

**Comment by flamewave000** [comment]
I have been informed that this could possibly be an issue with FoundryVTT using an outdated version of Electron. Apparently there is an issue with the update process where electron may not get updated properly when you update Foundry. If that is the case, it could explain why only a minority of people are affected. But also frustrating because there's no way for me to reproduce the problem on my computer 🥴

**Comment by DFreds** [comment]
@flamewave000 I don't think I've updated my base Foundry installation since 0.6.5. I can try to do so tonight and let you know if that resolves the issue for me.

**Comment by flamewave000** [comment]
@DFreds If possible, could you maybe ZIP your installation and send it to me? Just the `C:\Program Files\FoundryVTT` folder. Obviously keep the Foundry Data folder separate since that has your worlds/assets/license.

**Comment by flamewave000** [comment]
Thank you to @DFreds for sending me your installation. I was able to find the issue. It was indeed a problem with an outdated Electron. I've changed things to accommodate for this issue and will be putting a new release out shortly. Thank you everyone for helping me make Curvy Walls better 😄

**Comment by kamatikos** [comment]
> I have been informed that this could possibly be an issue with FoundryVTT using an outdated version of Electron. Apparently there is an issue with the update process where electron may not get updated properly when you update Foundry. If that is the case, it could explain why only a minority of people are affected. But also frustrating because there's no way for me to reproduce the problem on my computer woozy_face

I've done a fresh install of Foundry and the issue seems to have been resolved. It seems like Electron failing to update properly very well could be the cause.
