### ISSUE TITLE
DF Template Enhancements: Affected squares not highlighted when using Templates Auto-Target Tokens = Never" and  "Use D&D 5E Style Templates"

### ISSUE THREAD

**Issue by nschoenwald** [flamewave000/dragonflagon-fvtt#322]
**Module**
DF Template Enhancements 1.0

**Describe the issue**
When using the options "Templates Auto-Target Tokens = Never" and  "Use D&D 5E Style Templates", only one square is highlighted instead of all squares inside the template area.

**To Reproduce**
1. Activate "Templates Auto-Target Tokens = Never" and "Use D&D 5E Style Templates" options.
2. Create any template (occurs for all types).
I am using the current Foundry 9 hotfix version, current Chrome Browser and tested with no other modules active.

**Expected behavior**
All squares inside the template area should be targeted.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/72390280/157032310-8f68c52d-d7a0-4a8e-a0a4-093977b0e3b0.png)
![image](https://user-images.githubusercontent.com/72390280/157032372-6650a2f2-ab00-41df-883e-e9ac4defbb21.png)

**Comment by dmaneyapanda** [comment]
No squares get highlighted if both auto-target is Off and use dnd5e targeting is Off.  
<img width="173" alt="image" src="https://user-images.githubusercontent.com/2231877/157371415-194c97a0-78a8-425d-9a5b-bcb12e94f88e.png">

<img width="140" alt="image" src="https://user-images.githubusercontent.com/2231877/157371460-ba01fdfe-2016-468b-b09d-ea10f47c7338.png">

**Comment by flamewave000** [comment]
I'll reopen this ticket to investigate.

**Comment by flamewave000** [comment]
@dmaneyapanda I'm not able to reproduce your issue. You might have a module conflict.
![image](https://user-images.githubusercontent.com/3588046/157473333-2543cb60-b315-4df4-b0ac-c40ff2fd0eb3.png)

**Comment by flamewave000** [comment]
huh, yeah it looks like the 5e option bypasses the preview. Well good to know this ticket's bug is indeed resolved. I'll open a different ticket for the bug you found.
