### ISSUE TITLE
DF Template Enhancements: Cones are picking up targets from grid squares the template is not in

### ISSUE THREAD

**Issue by samgrieve** [flamewave000/dragonflagon-fvtt#325]
**Module**
DF Template Enhancements 1.0.0

**Describe the issue**
Using 5E templates and grid intersection snapping, cones are sometimes targetting tokens in spaces that the template is not inside of. Only appears to occur on the right hand side grid intersections of the casting token.

**To Reproduce**
1. Cast a spell with a cone template
2. Place the cone on intersections on the right hand side of the casting token
3. The caster and any tokens immediately above or below them will be targetted despite the template only being on grid spaces to the right of them.

**Expected behavior**
Only targetted tokens should be those within the template.

**Screenshots (Optional)**
video attached

https://user-images.githubusercontent.com/22322830/157113885-a1c53bc4-8e96-43e5-9ef9-3fa49adbe487.mp4

**Comment by flamewave000** [comment]
Could you check if those two tokens are scaled up? They look like they are extending outside the bounds of a single grid square. Someone reported a targeting issue with scaled tokens: #323

**Comment by samgrieve** [comment]
oh boy, not sure how I missed checking that! The caster was set to 1.3, setting that token to 1.0 stopped it targeting either token.

**Comment by flamewave000** [comment]
Alright, I'll keep this ticket open to track this issue since the other ticket has essentially two issues described.
