### ISSUE TITLE
DF Template Enhancements: Change cubes and squares to function as lines.

### ISSUE THREAD

**Issue by krbz999** [flamewave000/dragonflagon-fvtt#327]
**Is your feature request related to a problem? Please describe.**
A template that is a cube or square cannot be rotated and instead turns into a rectangle or 0-point-width line.

**Describe the solution you'd like**
A line (ray) template can be rotated. If a cube/square template worked just as a line with width equal to its length, it could be rotated as intended.

**Comment by flamewave000** [comment]
huh, I never actually tried rotating a square template before. They way it acts is just like a line, but highlights grid cells in a square. Might be something I can do about this.

**Comment by flamewave000** [comment]
Hopefully this matches what you were looking for.
![image](https://user-images.githubusercontent.com/3588046/157307699-57c5a11e-a17c-4805-b6c7-b51af21d3dd8.png)

The main caveat is that the template will now have to stay square. If you want a rectangle, you'll need to use a Ray with an adjusted width.

**Comment by krbz999** [comment]
Excited to try it. If this stays a square when trying to rotate a spell's template, then it's exactly what I was hoping for.

**Comment by flamewave000** [comment]
https://user-images.githubusercontent.com/3588046/157313960-273ddf2f-eea1-4f6f-8172-9aabd8e0c288.mp4
