### ISSUE TITLE
Do not work alongside MIDI using block walls

### ISSUE THREAD

**Issue by RavenknightDM** [flamewave000/dragonflagon-fvtt#329]
Hiya, thanks for the mod.

**Conflicting Module(s)**
MIDI QOL

**Describe the conflict**
I have Walls Block active in MIDI, used to work fine with DF - QOL, but now when I cast an AOE spell with the Target preview option it is very flickery and selects and deselects the target behind the wall even if it is well inside the template. Also when the spell is cast the is always affected even behind a wall.

**Comment by flamewave000** [comment]
So couple of things, MIDI has its own token targeting feature. There is an update that will be coming out for it (0.9.3+). In the meantime if you have DF QoL enabled, it should still trick MIDI into handling things correctly.

As for wall blocking, I don't currently do any sort of wall testing for auto-target. I would recommend disabling DF Template Enhancements token targeting feature when using MIDI's Walls Block feature.
