### ISSUE TITLE
DF Template Enhancement: Allow selecting how much (in %) of a square needs to be covered to be highlighted

### ISSUE THREAD

**Issue by nschoenwald** [flamewave000/dragonflagon-fvtt#330]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but it would be great to have.

**Describe the solution you'd like**
An additional option to select how much of a square needs to be covered by the area of effect (in %) for it to be highlighted. For example, I would like for squares to only be highlighted if at least 30% of their area is in the area of effect.

**Comment by flamewave000** [comment]
Unfortunately calculating the area of coverage would heavily increase the computations being performed. The best I could do is a feature similar to the gridless point grid and check if a certain number of points on the token are inside a template.

**Comment by nschoenwald** [comment]
I think checking the points would be fine, it's not necessary to choose any arbitrary percentage.

**Comment by flamewave000** [comment]
Ok so I have this working, but only for the Auto-Target feature. In order to also include the grid highlight I would need to perform some very heavy refactoring which I don't have time to do at the moment.
