### ISSUE TITLE
DF Template Enhancement: line template & grid snap

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#332]
**Module**
Hello,

using the 5e template style and grid snap, I wonder if a line template should actually be snapped to intersections?

![image](https://user-images.githubusercontent.com/1687854/157643216-9e057f5c-97a7-4707-8693-0319840d1373.png)

Doesn't feel right.

**Comment by flamewave000** [comment]
So this is technically RAW for D&D5e. a 5 ft wide line of attack will hit two creatures standing beside each other. The method of grid highlighting in Core FoundryVTT essentially cuts the efficacy of all line spells in half.

For example, a 15ft. cone can target 8-11 people depending on angle. A line 30ftx5ft (the most common size) would only ever be able to target 6 creatures. With this adjustment, a standard line spell will hit up to 12-15. Line spells also usually use a lower die when compared to similar cone spells, so this kind of balance makes sense when everything is considered.

Aside from all of that though, I designed it to be RAW, though for the purposes of allowing a DM to have freedom of choice, I can look into adding a way to set this property for each type of template. Similar to what I'm doing for the circle template.

**Comment by DarKDinDoN** [comment]
@flamewave000
Thx for the explanation! Sounds good to me.

But are you sure about the greedy part?

Straight from the DMG:
"Choose an intersection of squares or hexes as the point of origin of an area of effect, then follow its rules as normal. If an area of effect is circular and covers **at least half a square**, it affects that square."

**Comment by flamewave000** [comment]
Circles are the exception to the rule. All other AoE spells follow the base rule outlined in PHB p.204. If a straight line from the point of origin can extend unobstructed to a location, that location is hit. Circles are given that exception to the rule by the DMG, but I decided to add a separate option to also make the circles greedy and affect any square that is touched.

**Comment by DarKDinDoN** [comment]
I have found something about this in the Xgte P.86. It seems to correspond to the "Template method".
But then again, it's stated as an optional rule.

Could really find the subject online too.

To be clear, I prefer this method, I find it more intuitive.
But I'm curious, where did you see that it was the official way to translate a template to a grid?

**Comment by DarKDinDoN** [comment]
Finally, found something relevant from Crawford: https://twitter.com/jeremyecrawford/status/774037607097311232

So it's indeed the official way, just not really stated in the books.
Or something to deduct from the fact that circular AOE specially work the other way (DMG P.251), thus the rest of the AOE being greedy.

Not sure the description of the feature is right tho "_The D&D 5e PHB states that an space touched ..._".
The PHB doesn't actually state such rule.

**Comment by flamewave000** [comment]
So that line you copied is indeed the rule. It's worded in a very confusing way with a double negative. But if you inverse that double negative you get more easily understandable line I wrote above.

It was indeed confirmed by Crawford in that Twitter post.

**Comment by DarKDinDoN** [comment]
@flamewave000 Yeah, I figured that was what you were referring to.
Imo, that is kind of a stretch to consider the opposite of the sentence to a partially covered grid square (instead of at least 50 %).

But that's not really important.
Anyway, thank you for answering, I'm less confused about rules now 😸
