### ISSUE TITLE
DF Template Enhancements: Snap template size to grid

### ISSUE THREAD

**Issue by Spappz** [flamewave000/dragonflagon-fvtt#335]
Let's say you need to make a 5-tile-long line template. You drag out the template and let go with it at 5.2 tiles, since getting it exact on 5.0 is too much effort for your ~~lazy~~ hasty self. However, since you placed the origin of the line template slightly off-base (since you were once again ~~lazy~~ hasty), the template extends just far enough to hit the next tile, and actually covers 6 tiles!

This is a problem I've encountered a number of times, especially in D&D 5e while using the 'greedy template' rules. This suggestion would add a setting to force templates to snap their _size_ to the grid, in exact grid-units. So, as you drag out the template, the template jumps in increments of one tile; if 1 square = 5 feet, for instance, then the template is therefore constrained to multiples of 5 feet.

Heads-up that the [`pf2e`](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e) system already seems to have something like this, if there's code you can pilfer.

https://user-images.githubusercontent.com/34202141/158039692-51ff9fa6-df7c-4294-8277-8feb6ce64c22.mp4

**Comment by Spappz** [comment]
Just discovered [this](https://github.com/cdverrett94/FVTT-rounded-distance-for-measured-templates) module, which actually accomplishes the exact thing I'm looking for. You're welcome to close this if you don't see a point in supporting it 'natively', though even so I imagine it's not too hard to nab some code 😏

**Comment by flamewave000** [comment]
Yeah the "Rounded Distance for Measured Templates" module is actually one I use myself. I don't think I'll be integrating that feature right now since that module works well.
