### ISSUE TITLE
DF Chat Enhancements Better Scrolling "New Message! Scroll to Bottom" Only works for GM.

### ISSUE THREAD

**Issue by AtreidesGhola** [flamewave000/dragonflagon-fvtt#341]
**Module**
DF Chat Enhancements (3.6.0)
Foundry Version 9, Build 255

**Describe the issue**
Prevention of chat scrolling on entering a new message only works for GM.

**To Reproduce**
1. Start Foundry, Log in as GM.  Join as a player in another browser/computer
2. Scroll chat log back to read something previous.
3. Type chat message and commit from GM or other connected PC.  
4. All connected PC chats still scroll to the new message, regardless of origin (GM or other PC).  GM still gets the "New Message! Scroll to Bottom" bar, connected players don't.

**Expected behavior**
PCs get "New Message! Scroll to Bottom" bar instead of being returned to the bottom of the chat.

Tested further - it's a conflict with Midi-QoL.  Only occurs when that module is active.

**Comment by flamewave000** [comment]
This appears to be fixed. Either due to a change in my latest v3.6.1, or a change in Midi.
