### ISSUE TITLE
DF Chat Enhancements: Better handling of name attribution in Adventure Log

### ISSUE THREAD

**Issue by weepingminotaur** [flamewave000/dragonflagon-fvtt#343]
Currently, if a player saves a chat message from the GM to the adventure log, the saved entry lists the Gamemaster in parentheses even if the GM was emoting as an NPC to chat. And when emoting, the emote source is thrown into the text of the quote, which not only doesn't look great but makes it confusing to see, at a glance, who the speaker of the quote was. Lastly, the doubling up that happens in attribution when the Gamemaster saves a chat message, really doesn't look good. So, a few suggestions for improvement:

1. The token name should appear before the text of a saved message in the Adventure Log, not within it.
2. The Gamemaster should either never appear before the text of a chat message in the Adventure Log, or else we should have the option to turn it off.
3. We should have the option to turn off display of which player saved the chat message in the Adventure Log. Who saved a message is really not important. Having a player name or Gamemaster displayed before each message clutters up the log.

**Comment by flamewave000** [comment]
So I can do option 3, but the others would change the way that a Quote is intended to be written.
