### ISSUE TITLE
DF Chat Enhancements: option to disable chat message color outline

### ISSUE THREAD

**Issue by r-valyar** [flamewave000/dragonflagon-fvtt#346]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to completely disable the color outline in the messages with color matching player's color. The visuals are bad with such color exists and cannot be disabled. 

**Describe the solution you'd like**
I would like to have the ability to completely disable the color outline in the messages with color matching player's color. 

**Describe alternatives you've considered (Optional)**
Disable the module.

**Additional context (Optional)**
n/a

**Comment by flamewave000** [comment]
This is probably not something I will be adding. The easiest way to do this is to change the Player Chat Colour to the same colour for each player. This will effectively disable player colours in the chat as they will all look the same.

**Comment by flamewave000** [comment]
I decided to reverse my decision on this. I saw an easy way to do it with my existing code, so I added it in as an option in Module Settings.
