### ISSUE TITLE
DF Scene Enhancement: Conflict with Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by jacksands** [flamewave000/dragonflagon-fvtt#347]
**Conflicting Module(s)**
- Monk's Active Tile Triggers

**Describe the conflict**
I receive constant warnings from libWrapper about "potential conflict" haven't seen any bug so far, I just like to warning you about that, perhaps it helps this amazing module!

**Expected behavior**
Like I say above, just the libWrapper warnings 

**Screenshots (Optional)**
I have lost the Screenshot of the game screen but sending you the console.

![Screenshot 2022-03-26 073406](https://user-images.githubusercontent.com/7229143/160235633-4d1dc924-30e8-4ef9-a97e-653f564feb44.jpg)

**Comment by KammaKhazi** [comment]
I get similar conflict warnings about these two modules...mine looks as follows.
![conflict](https://user-images.githubusercontent.com/81476445/164984082-f05c4755-7e12-4683-b3d1-4d27d763275c.png)

**Comment by flamewave000** [comment]
There's not really a way around this issue. I have a MIXED wrapper for this function. If I were to call the original function then it would display the SceneConfig, so instead I override when you click a scene to prevent this behaviour. It looks like MATT also has a MIXED wrapper.

**Comment by jacksands** [comment]
I appreciate the effort and the time!
