### ISSUE TITLE
Releases direct always to last version, unable install previous

### ISSUE THREAD

**Issue by Renanrmx** [flamewave000/dragonflagon-fvtt#349]
**Module**
All modules releases
Also occurs in other repositories

**Issue**
Unable to install previous version from releases, fields "manifest" and "download" direct to [https://dragonflagon.cafe](url) with last version, unsupported for certain Foundry versions.

**Code example of Curvy Walls 3.2.3**
...
`
"manifest":	"https://dragonflagon.cafe/mods/man/df-curvy-walls",
`
`
"download":	"https://dragonflagon.cafe/mods/pak/df-curvy-walls",
`
...

**Expected behavior**
On release module.json change the fields "manifest" and "download" to the .zip and .json of actual release.
...
`
"manifest":	"https://github.com/flamewave000/dragonflagon-fvtt/releases/download/df-curvy-walls_3.2.3/module.json",
`
`
"download":	"https://github.com/flamewave000/dragonflagon-fvtt/releases/download/df-curvy-walls_3.2.3/df-curvy-walls.zip",
`
...

**Comment by flamewave000** [comment]
I don't use the releases for my distribution. All installation goes through my distribution server which will automatically modify the manifest for appropriate version ING. If you wish to use a specific version you can use the following link:

https://dragonflagon.cafe/mods/man/<module-id>@<version>

For example, if you want DF Curvy Walls version 3.2.3, you use the following:

https://dragonflagon.cafe/mods/man/df-curvy-walls@3.2.3
