### ISSUE TITLE
DF Template Enhancements: error when opening the templates measures settings

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#350]
**Module**
DF Template Enhancements 1.2.0

When trying to open the templates measures settings
![image](https://user-images.githubusercontent.com/1687854/161656148-6cd87362-8e9e-464c-a415-ec0fe8b2c88f.png)

**Comment by flamewave000** [comment]
![WhatAreYouTalkingAboutHuhGIF](https://user-images.githubusercontent.com/3588046/161656360-61be0868-5482-4a4e-ad12-b4ce15899c54.gif)

**Comment by flamewave000** [comment]
It appears to be working fine for me, not sure what's going on for yours. Maybe a module conflict? Could you try opening it with other mods disabled?

**Comment by DarKDinDoN** [comment]
@flamewave000 No other modules.

Error on this as well : `game.i18n.translations['DF_TEMPLATES']['TemplateConfig']['Options']`
![image](https://user-images.githubusercontent.com/1687854/161658278-cd866416-01f7-4e97-a0f7-8aebefaa7695.png)

Maybe because I had an older version? Issue with the migration or smt?

**Comment by DarKDinDoN** [comment]
Maybe because I'm not playing with the default language?

**Comment by flamewave000** [comment]
@DarKDinDoN what language are you using? I only have partial translations for Japanese (community submitted).

**Comment by flamewave000** [comment]
Ok, that's very very weird. I'll have to figure out how to change my localization to test this. My understanding is that if the language is not supported, it should default to the english language file.

**Comment by DarKDinDoN** [comment]
@flamewave000 just go to the settings in game and change the language :D
