### ISSUE TITLE
Add Token Locking please.

### ISSUE THREAD

**Issue by 00zim00** [flamewave000/dragonflagon-fvtt#357]
Since DF Template Enhancements is a replacement for DF Quality of Life. Is it possible to gain back the Token Locking feature that DF Quality of Life had?

DF Quality of Life had a Token Locking feature that was extremely helpful for NPCs that i didn't want to click by accident mid battle. OR to lock tokens that I use as shop or landmark icons.

I am unaware of any of mod that has this feature and so would be greatly appreciative.

Thank you!

**Comment by flamewave000** [comment]
So DF Template Enhancements is Not a replacement for DF QoL. I simply extracted the template features into their own module. DF QoL is still fully functional and maintained.
