### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#36]
Hello,

Looks like all your module can't be installed with the message "Did not provide a valid manifest file."

**Comment by ComedianTF2** [comment]
Same issue

**Comment by jessev14** [comment]
Trying to install using the manifest url in the releases returns a Bad Gateway error.

**Comment by flamewave000** [comment]
Sorry everyone. I'm using a proxy for the download links so it is easier to have a "static" location where updates are delivered. I went to bed thinking all was well, but clearly it had a problem 🤦‍♂️It's back up now 👍
