### ISSUE TITLE
DF Scene Enhancement - Prevent players from accessing scene options?

### ISSUE THREAD

**Issue by Doresain** [flamewave000/dragonflagon-fvtt#38]
Hey there, great module concept. 

Would love to see a method to prevent players from accessing the right-click menu on scenes (Config, Import/Export, etc), allowing only for left-click navigation. As it is I'm nervous about allowing them access to scene config.

**Comment by flamewave000** [comment]
Thanks for bringing this to my attention. The player is NOT supposed to have access to those options in the menu. This is likely something that changed between 0.7.5 to 0.7.9 and I never noticed. I'll look into this ASAP.

**Comment by flamewave000** [comment]
Ok this should be fixed. I've pushed a 3.3.0 release.

**Comment by Doresain** [comment]
Tested, can no longer reproduce, as expected. Thanks man.
