### ISSUE TITLE
DF Quality of Life: Conflicting with Dorako UI for PF2

### ISSUE THREAD

**Issue by apoapostolov** [flamewave000/dragonflagon-fvtt#382]
The CSS class dfqol-better-toggle is in conflict with how Dorako UI for PF2 skins the switches in active state, causing them to appear purple instead of bright blue as set by Dorako UI. Unfortunately, this class cannot be turned off in the module settings. A setting to turn it off would greatly help.

How it should look

![image](https://user-images.githubusercontent.com/4083812/177413976-cfd49e0b-0200-493e-aac2-bbc5ab43d90a.png)
How it looks

![image](https://user-images.githubusercontent.com/4083812/177413724-cf80e118-4f29-42cd-88b3-8e304137d1af.png)

**Comment by flamewave000** [comment]
Hey, I just realized this already has a solution. There is an option in the module settings to disable my styling.
![image](https://user-images.githubusercontent.com/3588046/196071925-d30e72e3-41e4-4870-ad01-f03f5474c27a.png)
This will completely remove my css styling and prevent any conflict.
