### ISSUE TITLE
DF Chat Enhancements: Could not create archive

### ISSUE THREAD

**Issue by miromonti** [flamewave000/dragonflagon-fvtt#385]
**Module**
DF Chat Enhancements v4.0.0

**Describe the issue**
This is my first time using the module and I want to archive all chat up to two sessions ago. First session was October 26, 2020.

My first attempt, I left From Date empty, thinking DFCE would automatically select whatever is at top of chat. Then I chose a few hours after game on last date to ensure any chat before next session is archived:
![Screen Shot 2022-07-14 at 10 10 13 PM](https://user-images.githubusercontent.com/38819125/179155609-7d12eae5-2708-415b-b40f-1c1a5e46fe56.png)

A little time passed and an alert indicated that the archive was created. However, Manage Chat Archive showed nothing. I checked the archive folder in the game world and it's empty. The console showed this error:
![Screen Shot 2022-07-14 at 9 59 53 PM](https://user-images.githubusercontent.com/38819125/179155957-63d2c70c-24ec-4dc5-a0bb-6b6d79ac5b09.png)

My second attempt, I chose for From Date the date of the first session, with time a few hours ahead of that session. Again, I chose a few hours after game on last date to ensure any chat before next session is archived:
![Screen Shot 2022-07-14 at 10 12 11 PM](https://user-images.githubusercontent.com/38819125/179158229-bd28306d-e870-4ce3-9262-2a294741c150.png)

Again, a little time passed and an alert indicated that the archive was created. However, Manage Chat Archive showed nothing. I checked the archive folder in the game world and it's empty. The console showed this error:
![Screen Shot 2022-07-14 at 10 39 06 PM](https://user-images.githubusercontent.com/38819125/179158257-63f81813-a618-42b0-a9d2-8a08ba3fb9e8.png)

I don't know what I'm doing wrong. The process seems self-explanatory: 

1. Create and choose an archive folder.
2. Fill the necessary spaces.
3. Click Save Archive.

But, errors.

**Comment by miromonti** [comment]
Resolved. Turns out my VPN was interfering. I disconnected it and DFCE worked as expected.

For those wondering, a chat that goes back over 600 days does take a little time. Nothing seems to happen, and then it does.

**Comment by flamewave000** [comment]
Thanks for the follow up on this. Good to know what the cause was :+1:
