### ISSUE TITLE
DF Template Enhancements: Error in Foundry v10

### ISSUE THREAD

**Issue by Kharmans** [flamewave000/dragonflagon-fvtt#392]
**Module**
DF Template Enhancements v1.2.1

**Describe the issue**
With the module active, when use anything that create a measure template, the foundry crashes, it's impossible to open the map with that template and the error bellow appear in console.

**To Reproduce**
1. Active DF Template Enhancements
2. Use anything that create a measure template, include the measure templates tool of Foundry
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/112586547/189503821-e29ff65d-6ef0-4215-91fb-38cec09b26f8.png)

**Comment by geoidesic** [comment]
I can confirm that this causes the scene tray to appear empty.

**Comment by Severem** [comment]
There is a way to return the Scene even after the error.  Go back to Manage Modules under Settings and Turn off the DF Templates Module.  This should return your Scene as it was before, but will also show all the templates that was drawn before the error.  It's easy enough to delete them off though.
