### ISSUE TITLE
DF Chat Enhancement: Chat Images conflict

### ISSUE THREAD

**Issue by dstein766** [flamewave000/dragonflagon-fvtt#395]
**Conflicting Module(s)**
- Chat Images v3.1

**Describe the conflict**
When Chat Images is ENABLED and DFCE is DISABLED, you can insert an animated GIF into chat using the (Chat Images-enabled) syntax !ci!&lt;url&gt;!.
When DFCE is enabled, this gets broken.  Instead of showing the animated GIF, the chat log displays brokenImageGraphicURL" alt="Unable to load image"&gt;

Note that brokenImageGraphic is used here as a placeholder for the actual graphic, and there is NO leading less-than sign at the start of the line shown in the chat log.  Further, there appears to be no leading quote mark between the broken image graphic and the URL, but there IS a closing quote immediately after the URL.

I have tried turning off all of these options in DFCE:
* Chat Merge: Enable Chat Message Merging (I assume all other Chat Merge: settings are ignored if this is off)
* Chat Merge: How to Handle Rolls when Merging (tried "Do not merge")
* Enable Chat Scroll Improvements
* Scroll To Bottom When You Send Message

* Chat Message Tinted Borders (tried No border tinting)
* ALWAYS OFF for me: Tint Chat Message Background, Use Simple Calendar for Chat Timestamps

**Expected behavior**
entering the following into chat should display the animated GIF found on Chat Image's own Readme page:
!ci|https://github.com/bmarian/chat-images/raw/master/readme/example.gif!

**Screenshots (Optional)**

**Additional context (Optional)**
FVTT v10.285, DND5e v2.0.2, DFCE 4.0.0, Chat Images 3.1

**Comment by flamewave000** [comment]
This is most likely a conflict with what Chat Image in putting into the chat message. DF Chat enhancements adds MarkDown formatting to the chat, so you can enter regular MarkDown, as well as HTML into the chat and it will render accurately.

For your use case, sending an image to the chat using DFCE's markdown would be as follows:
```md
![](http://domain.com/path/image.png)
```

**Comment by dstein766** [comment]
The alternate markdown syntax does, indeed, work around the issue for 
me.  Thanks!

>Message ID: 
***@***.***>
>
