### ISSUE TITLE
DF Curvy Walls not working with V10

### ISSUE THREAD

**Issue by kagedansa** [flamewave000/dragonflagon-fvtt#397]
**Module**
DF Curvy Walls V3.3.1

**Describe the issue**
The module isn't working with Foundry V10 any more

**To Reproduce**
Try to create a wall with any function of the module (e.g. Ellipse Curve)

**Expected behavior**
Work as in V9

Console-log attached.
[localhost-1664094897456.log](https://github.com/flamewave000/dragonflagon-fvtt/files/9640314/localhost-1664094897456.log)

**Comment by CaosFR** [comment]
@flamewave000 Hi and thanks for your work. Can we have a timeline for the update to v10 ?

**Comment by flamewave000** [comment]
DF Curvy Walls in pre-release for v10
