### ISSUE TITLE
DF Chat Enhancements: Adventure log no longer works in V10

### ISSUE THREAD

**Issue by Fyrexian** [flamewave000/dragonflagon-fvtt#398]
**Module**
DF Chat Enhancements 4.0.0
**Describe the issue**
When trying to quote or log an event, it fails to put it into the journal now.

**To Reproduce**
1. Right click chat message
2. Click Adventure log as an event or quote
3. See error

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/47077661/192384008-50e5a29b-38c4-4927-8b24-b0ce1fc7ebdb.png)

**Comment by joetheory** [comment]
Came here for the same reason.

**Comment by marcstraube** [comment]
Logging via /log and /gmlog commands also does not work. The Adventure Log stays empty. No errors in console.
