### ISSUE TITLE
0.7.5 Changing scene background image freezes application

### ISSUE THREAD

**Issue by kelsa-gm** [flamewave000/dragonflagon-fvtt#4]
When DF Scene Enhancement is the only module installed in 0.7.5, if you change the background image of a scene and press 'Save Changes', the whole application freezes, and must be force closed.

**Comment by Bryn1701** [comment]
I too am experiencing this. Tested with no other modules installed. Even changing the token sight or global illumination and clicking save will result in the same freeze that must be force closed.

**Comment by flamewave000** [comment]
Updated module to no longer have any issues in 0.7.4+. Try out Version 2.0 and let me know if you run into any issues. Thanks for enjoying my module :)
