### ISSUE TITLE
Update broken

### ISSUE THREAD

**Issue by spirritus** [flamewave000/dragonflagon-fvtt#40]
When hitting the "check update" button in foundry the following message apepars:

`The request to https://github.com/flamewave000/dragonflagon-fvtt/releases/download/df-scene-enhance_3.1.1/module.json did not provide a valid manifest file.`

**Comment by flamewave000** [comment]
You have an older update. I changed the update flow and deprecated anything older than 3.2. You'll need to just reinstall the module.
