### ISSUE TITLE
DF User Logger - "The key (x) does not exist in the Messages Collection"

### ISSUE THREAD

**Issue by Doresain** [flamewave000/dragonflagon-fvtt#400]
![image](https://user-images.githubusercontent.com/26096062/193477768-65a93e1a-6a6a-4bf4-98f0-72c0d2b980a9.png)

I haven't been able to pin down how to reproduce the error reliably, and it doesn't seem to break any functionality, but it occasionally appears after a user connects or disconnects.

**Comment by flamewave000** [comment]
Yeah I've seen this. It usually occurs if you delete the message before the module's timer does. It indeed should not cause any issues, but I plan on redoing some of this module to run a little bit better. It was my first module and I've obviously learned a lot since then.
