### ISSUE TITLE
chat enhancements: get error about archives in v10

### ISSUE THREAD

**Issue by dharkus5000** [flamewave000/dragonflagon-fvtt#403]
**Module**
DF Chat Enhancements - v4.0.0

**Describe the issue**
get the following error in console
`Uncaught (in promise) Error: Could not access the archive folder: worlds/kingmaker/chat-archive
[Detected 1 package: df-chat-enhance]
    createArchiveFolderIfMissing DFChatArchive.ts:124
DFChatArchive.ts:124:11`

**To Reproduce**
login to world 

**Expected behavior**
get no errors!

**Comment by dharkus5000** [comment]
just deactivated the following modules:
library: DF hotkeys
PF2e Lootgen
PF2e Toolbox
PF2e Inspire Courage Button
Keybind Lib
and the error morphed - it's now this
`Uncaught (in promise) Error: Could not access the archive folder: worlds/kingmaker/chat-archive
[Detected 2 packages: df-chat-enhance, lib-wrapper]
    createArchiveFolderIfMissing DFChatArchive.ts:124
    createArchiveFolderIfMissing DFChatArchive.ts:122
    registerSettings DFChatArchive.ts:116
    init df-chat-archive.ts:12
    <anonymous> df-chat-enhance.ts:38
    #call foundry.js:724
    callAll foundry.js:681
    initialize foundry.js:7712
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:78838
    async* foundry.js:78820
DFChatArchive.ts:124:11
`

**Comment by CaosFR** [comment]
@flamewave000 Hi and thanks for your work. Can we have a timeline for the update to v10 ?
