### ISSUE TITLE
DF Curvy Walls v3.3.1: walls cannot be drawn

### ISSUE THREAD

**Issue by Elmoserpe** [flamewave000/dragonflagon-fvtt#404]
**Module**
DF Curvy Walls v3.3.1

**Describe the issue**
Walls can't be created while the module features are enabled.

**To Reproduce**
1. Go to 'Wall Controls'
2. Click on 'Draw Walls with any feature active'
3. Try and draw a wall

**Expected behavior**
Walls should be drawn while using Cubic Bézier Curve, Quadratic Bézier Curve or any module feature.

**Comment by flamewave000** [comment]
I assume this is for V10. This is fixed in pre-release
