### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by HippyCraig** [flamewave000/dragonflagon-fvtt#41]
When updating mods I get the following, I even tried uninstalling and reinstalling the mod but I still see this:

![image](https://user-images.githubusercontent.com/17074456/107259858-85636400-6a0b-11eb-99f3-280e8dc89638.png)

**Comment by flamewave000** [comment]
Duplicate of #40
You will need to reinstall the module using the foundry listing, or the following manifest url
[https://dragonflagon.cafe/mods/man/df-scene-enhance](https://dragonflagon.cafe/mods/man/df-scene-enhance)

**Comment by HippyCraig** [comment]
Thanks, sorry for the dup
