### ISSUE TITLE
DF Templates 1.3.0 - providing the manifest in V10 installs 1.2.1 instead

### ISSUE THREAD

**Issue by apoapostolov** [flamewave000/dragonflagon-fvtt#411]
I take the manifest from https://github.com/flamewave000/dragonflagon-fvtt/releases/download/df-templates_1.3.0/module.json

This causes V10 to install 1.2.1 instead.

**Comment by flamewave000** [comment]
It's currently in pre-release so it won't install by that URL since manifest installs go through my distribution service.
