### ISSUE TITLE
DF Chat Enhancements: additional chat mode bar options

### ISSUE THREAD

**Issue by apoapostolov** [flamewave000/dragonflagon-fvtt#42]
The height of the chat mode buttons causes the row above the text input field to grow in height and the original icons around them will have a lot of margin-top and bottom. This looks a bit jarring, so it is possible to convert all the icons on the line into buttons in the same way the dropdown menu was converted into buttons? This will cause no logical difference in button height and presentation. 

In addition, option to hide some of the icons on that row would be much appreciated:
- the ability to remove the die button before the chat mode buttons - for people who use dice tray mod
- the ability to remove the export chat button especially when it can be moved to the new archive functionality.

With these options one could have the following options on his chat mode bar: the modes (public, private, gm...) and a new button for the archive, and an old button to clean chat, also styled as a button in that bar.

**Comment by flamewave000** [comment]
So a couple of thoughts.
1. The d20 on the left side of the bar is not a button in Core. I believe that is being changed by Dice Tray. In core it's just a static icon that acts as a "label". This behaviour is being changed by Dice Tray, which may cause a conflict/race condition if I were to also try to change the same element. It is possible, but I'd have to try and Hook into the Dice Tray mod's functionality.
2. I can definitely add a setting to remove the Core save button. It's also not a bad idea to include it in the archive manager 👍
3. I'll look into swapping out the hotlink icons for actual buttons.
Also, after testing the DiceTray, it appears to be doing something odd with the d20 icon, their CSS is also affecting the d20 icon in the public roll button. I may open a ticket with that project about the issue.

**Comment by apoapostolov** [comment]
Hello, thanks for sharing your thoughts.

1. I think it is fine to ignore the Dice Tray button, I will contact its dev to ask if it can be made optional, or if not I will see if I can remove it via CustomCSS mod.
2. I would like to propose that you completely remove the Core Export and Clean buttons and add Archive and Clean buttons in your button UI format. The export functionality can be moved as part of exporting each session in the archive. The clean button is very useful and can stay, but duplicated in your CSS format.

**Comment by flamewave000** [comment]
I've opened a ticket with them on the odd highlighting issue as well
[#19 Highlighting DF Chat Enhancement D20 icon on hover](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator/-/issues/19)

**Comment by flamewave000** [comment]
This is looking pretty good I think

![image](https://user-images.githubusercontent.com/3588046/107565800-11af8b80-6bb2-11eb-8711-3e9db0642fb7.png)

Just need to add the settings for toggling things.
