### ISSUE TITLE
DF Chat Enhancements: Chat Images

### ISSUE THREAD

**Issue by MrVauxs** [flamewave000/dragonflagon-fvtt#423]
**Conflicting Module(s)**
- [Chat Images](https://github.com/bmarian/chat-images)

### **Describe the conflict**
**Roll Buttons: Use buttons style on all chat buttons:** 
![image](https://user-images.githubusercontent.com/32039708/202256628-ec67ff7c-269f-4477-86be-c1308c79f47d.png)
**Roll Buttons: Replace roll type selector with buttons only:** 
![image](https://user-images.githubusercontent.com/32039708/202256798-07c7e360-21b8-4655-a261-afa1e4732819.png)
**None of the above:**
![image](https://user-images.githubusercontent.com/32039708/202256870-0427ad27-1cf8-4308-bd33-b402647a3c3e.png)

**Expected behavior**
The buttons do not overflow.

**Comment by p4535992** [comment]
also seem to broke something when i applied the code `!ci|https://i.imgur.com/xxx.jpg!` on the chat i generate this outer html.

```
<div class="ci-message-image"><img src="<a href="><a class="hyperlink" href="https://i.imgur.com/xxx.jpg&quot;" target="_blank" rel="nofollow noopener">https://i.imgur.com/RAH98JT.jpg"</a> alt="Unable to load image"&gt;</div>
```

this is wrong `src="<a href=">` same for when i upload a image.

**Comment by flamewave000** [comment]
So DF Chat Enhancements is not meant to be used along side Chat Images as they both provide the same functionality. DFCE includes full standard Markdown support in chat, so you can use `![my image](https://i.imgur.com/xxx.jpg)` and it will add that as an image to the chat.

If you wish to keep them both, please use the second styling option so as to not overflow the buttons.

**Comment by MrVauxs** [comment]
I will note that Chat Images also allows for image upload, so the functionality is not 100% the same. But I will see if there could perhaps be a PR done to bridge the gap.

**Comment by MrVauxs** [comment]
Note: [PF2e Dorako UI](https://github.com/Dorako/pf2e-dorako-ui) has fixed this issue already.
![image](https://user-images.githubusercontent.com/32039708/204383699-6416fb26-12ab-472a-8c66-4d7b448ca5ef.png)

**Comment by flamewave000** [comment]
@MrVauxs it looks like he does so by removing the D20 icon. Be warned that this will conflict with Dice Tray which uses that icon as a button to display the dice calculator. If you don't use Dice Tray, or care about using that feature, then Dorako is fine :+1:

**Comment by MrVauxs** [comment]
I have noticed and even noted that. I believe they said they enable the
button back when Dice Tray is on, but I don't know how it conjucts with
Chat Images.

Though in the end, I don't use Dice Tray lol

pon., 5 gru 2022, 00:09 użytkownik flamewave000 ***@***.***>
napisał:
