### ISSUE TITLE
DF Chat Enhancements: Cannot configure Journals for Adventure Log

### ISSUE THREAD

**Issue by marcstraube** [flamewave000/dragonflagon-fvtt#434]
**Module**
DF Chat Enhancements 4.1.0
Foundry Version 10.291

**Describe the issue**
I tried to configure the Journals for the Adventure Log and GM Adventure Log, but I cannot choose any Journal.

**To Reproduce**
1. Create new world.
2. Enable DF Chat Enhancements and Chat Commands Library.
3. Create new Journals.
4. Open settings and try to choose one of the newly created Journals.

**Comment by jazzman831** [comment]
After you create a journal, did you create a page within that journal? I had this same issue until I added pages.

**Comment by marcstraube** [comment]
> After you create a journal, did you create a page within that journal? I had this same issue until I added pages.

Thanks a lot, that worked!
