### ISSUE TITLE
Issue [PF2E]: Skipping User Input Prompt for Critical Rolls 

### ISSUE THREAD

**Issue by 117ksk** [flamewave000/dragonflagon-fvtt#453]
Looks like all critical rolls made with any weapon in the PF2e game system skip "Rendering RollPrompt" and just jump to rolling a random result. All normal damage rolls from weapons prompt the user correctly only breaks with critical damage rolls. I have also been able to recreate this "prompt skip bug" with various spell damage rolls such as with Acid Splash (rolling damage directly from spell card in chat).

**Comment by flamewave000** [comment]
If you enable the "Legacy" mode in DF Manual Rolls and you get a browser prompt for those rolls, then this is an issue with the game system which is not using `async` for those specific rolls.

**Comment by 117ksk** [comment]
I also had this thought and attempted to enable "Legacy" mode. Unfortunately after doing so, the "Critical" damage roll simply breaks and no roll is either prompted for nor rolled at all. I also found the following error in the log everytime the "Critical" damage roll is attempted while "Legacy" mode is enabled: 
![image](https://user-images.githubusercontent.com/113755707/220437784-4ab83b82-e813-43a6-82af-6b67d88a8b37.png)

And this error is found every time I attempt a "Acid Splash" spell damage roll while "Legacy" mode is enabled:
![image](https://user-images.githubusercontent.com/113755707/220438102-15c317f3-8b04-41d4-91d6-25bb418b75bb.png)

Last thing to point out, after enabling "Legacy" mode and then disabling it again results in the broken critical and spell damage roll bug (simply no roll at all and above errors in log) to persist until the game is reloaded. Hopefully this helps, let me know if you would like me to test anything else for troubleshooting.

**Comment by flamewave000** [comment]
Ahh yes, this error is because you are trying to use Legacy mode from within the FoundryVTT Client that gets installed instead of an actual browser. The client is essentially just a browser called "Electron" and for some baffling reason they decided to not implement the "prompt()" function (available on every browser since literally 2001). Very frustrating but nothing we can do about that.

Simply launch your foundry and then open a browser and sign in to your `http://localhost:30000`

**Comment by 117ksk** [comment]
Understood. Confirmed prompts for critical and mentioned spell damage works with Legacy mode turned on and in browser only. Thanks!
