### ISSUE TITLE
DF Active Lights 1.3.1 No longer functioning with Foundry 10.2.9.1

### ISSUE THREAD

**Issue by Melephisance** [flamewave000/dragonflagon-fvtt#458]
**Module**
DF Active Lights 1.3.1

**Describe the issue**
Animations have ceased to work with Foundry 10.2.9.1
My previously created animations are now not functioning.

**Comment by flamewave000** [comment]
It's hard to say. I'm running 10.291 right now and my animations are still working in my DnD5e test world. You might be having an conflict issue. Could you try disabling all of your other mods except the DF Active Lights?

If your animations start working again, then another mod is the problem and you can use the mod "Find the Culprit!" to narrow down which one is the problem.

**Comment by Melephisance** [comment]
Hello - thanks for the reply. I tried this, removed all the mods and left DF Active Lights and the issue remains. It is rather frustrating.
I likewise created a new game and added the mod and it worked fine so if I am honest I am rather clueless what the problem is. 
I appreciate this helps not one bit!

**Comment by flamewave000** [comment]
Could you open the browser's console to see if there are any errors there? Just press F12 and it should open a window that shows the "Console". Just scroll up through that and any errors will be highlighted in red.

**Comment by Melephisance** [comment]
"Foundry VTT | Unregistered callback for lightingRefresh hook" - is this significant?

**Comment by flamewave000** [comment]
I don't believe so, I don't have any references to that. If you have some errors, could you post a screenshot of them? Also, maybe you can send me screenshots of the frames on one of your animation configurations that's not working.

**Comment by Melephisance** [comment]
![Screenshot 2023-03-11 161834](https://user-images.githubusercontent.com/96983231/224495509-9f1e047d-bb47-4761-abab-95209e8ac664.png)
![Screenshot 2023-03-11 161811](https://user-images.githubusercontent.com/96983231/224495511-78738a61-70a7-4692-9002-1d0866c24c7b.png)

No errors appear in the console...
Thanks so much for your help.

**Comment by Melephisance** [comment]
Hello again - so I remain clueless as to why this isn't working. I am prepared to give youself or a member of your team access to my game to be able to investigate and would be willing to pay for your time. Thank you in advance for any assistance you would be prepared to give. I would love to have this module working in my game again - it really was one of my favourites!

**Comment by flamewave000** [comment]
Marking this as resolved with the discovery of the toggle switch being off 👍🏽
