### ISSUE TITLE
Chat-Enhancement: conflict with emoji module

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#46]
Hello,

When emoji module (https://github.com/Moerill/emojule) is enabled the journal note as some broken images:
![image](https://user-images.githubusercontent.com/1687854/108046674-2f16a680-7045-11eb-9ab1-effd16a669fc.png)

**Comment by flamewave000** [comment]
I just installed Moerill's emoji module and tried it and I don't see what you're showing.
![image](https://user-images.githubusercontent.com/3588046/108120579-7fa2f980-706f-11eb-984c-490624eb2701.png)

**Comment by flamewave000** [comment]
Ah nevermind, I didn't notice the little "un" by the timestamp. I'll see if I can figure out what's happening. But this looks like a bug with the Emoji module injecting something into the log and I may not be able to correct it.

**Comment by flamewave000** [comment]
Actually that is exactly what's happening. The Emoji module is seeing the `:` and trying to inject an emoji without actually looking to see if there should be one there. You'll have to open a ticket with https://github.com/Moerill/Emojule

**Comment by DarKDinDoN** [comment]
Thx, I just submitted an issue: https://github.com/Moerill/Emojule/issues/5
