### ISSUE TITLE
Chat-Enhancement: hidden messages

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#47]
Hello,

As the GM I would like to enter privates notes to my log. But if the "hidden message/roll" button is checked in the list of role types, the message displayed in the chat is still public.
![image](https://user-images.githubusercontent.com/1687854/108046969-89b00280-7045-11eb-8efb-4a66d2e504ce.png)

**Comment by flamewave000** [comment]
I'll add a toggle to turn off the chat messages. I can look at the Roll Types, but because the message is not a roll, the best I can do is make a Whisper to yourself if anything but "Public" is selected.

**Comment by DarKDinDoN** [comment]
@flamewave000 whipser is good!
