### ISSUE TITLE
DF Scene Enhancement: Scene Config Menu — FXMaster, AboutTime, and Weather Effects

### ISSUE THREAD

**Issue by Greysion** [flamewave000/dragonflagon-fvtt#48]
Hey,

Just a quick notice that this mod has some conflicts with the suite of the Weather/Time effects on scenes.

Using the mods above, you can set scenes to automatically change day/night cycles based on the time, on a per scene basis. Unfortunately, when you enable this mod, it over rights that feature in the options menu because it changes the same scene config menu for the grid-scale.

I know it's not top of your priority, but it would certainly be a welcome fix.

There's also a much more minor UI issue with the same settings menu when using a UI revamp like Modern UI. The boxes go full-width sized and I'm not sure if that's fixable?

**Comment by flamewave000** [comment]
Unfortunately if you are using a UI revamp, it would be up to the revamp module maker to fix any conflicting issues as they are essentially overriding all of the styling of Foundry.
