### ISSUE TITLE
DF ManualRolls PF2e Damage Rolls

### ISSUE THREAD

**Issue by minoroctave** [flamewave000/dragonflagon-fvtt#483]
**Module**
DF ManualRolls v 2.4.0

**Describe the issue**
Attempting to roll damage in PF2e while any static bonus applies (from any source that I have tested), it does not prompt with the manual entry. All d20 roll requests work as intended including any with static bonuses, damage roll requests with static bonuses roll automatically without any prompt (unless using Legacy Rolling support, which throws a substantial error instead).

**To Reproduce**
1. Use PF2e system with this module
2. Set manual rolls to "always" or toggled on through the toggleable button
3. Roll any damage roll with a static bonus (strength bonus, weapon flat damage bonus, etc.)

**Expected behavior**
Popup box appears like with any other rolls (or with any rolls that don't have a static bonus), allows you to enter the value.
(Have tested, and static roll bonuses work in the 5e system)

**Comment by flamewave000** [comment]
This is a known issue with the PF2e system that cannot be fixed by DF Manual Rolls. See #470
