### ISSUE TITLE
Conflict Chat Commands vs system DSA5

### ISSUE THREAD

**Issue by Danii0206** [flamewave000/dragonflagon-fvtt#49]
Hi,
since the Chat Enhancements use Library: Chat Commands as a dependency it is no longer compatible with the system DSA5. I messaged both of them, but don't know if it is fixable. So... just so you know. 
Kind regards
Danii

**Comment by flamewave000** [comment]
With the way the module runs, you can still use it without Chat Commands. You just won't be able to use the Adventure Log feature. Everything else will run normal
