### ISSUE TITLE
DF Chat Enhancement: Ability to add to adventure log from chat log if you forget /log when displaying a chat message

### ISSUE THREAD

**Issue by tposney** [flamewave000/dragonflagon-fvtt#50]
A context right mouse click or message button to add a chat message to the journal.
If a message is displayed to players and they think it worthy of adding to the journal, it would be nice to simply click on the message and have it logged to the adventure log.

**Comment by flamewave000** [comment]
I will look into this when I do a larger update to the Chat Archive. I plan to add some more QoL to the feature.
