### ISSUE TITLE
DF Chat Enhancement: issue with settings

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#51]
Hello,
When I try to modify the settings, I get:
![image](https://user-images.githubusercontent.com/1687854/108261906-83fd0e80-7164-11eb-9fd4-cfe0a08bd5ac.png)

**Comment by flamewave000** [comment]
Make sure you have the latest version of the Chat Commands library installed.

**Comment by DarKDinDoN** [comment]
@flamewave000 I have: 1.3.0

**Comment by flamewave000** [comment]
Could you send me what your settings are for the module? I'm not currently able to reproduce the error. I wonder if I'm just not using the right combination of settings.

**Comment by DarKDinDoN** [comment]
@flamewave000 As soon as I select the one in the screenshot and save, I have this error.
![image](https://user-images.githubusercontent.com/1687854/108274315-042b7000-7175-11eb-9bff-0c5211dcfb50.png)

**Comment by flamewave000** [comment]
Ha ok, I got it reproducing now. Did not have the right combo of settings. I'll look into it :+1:

**Comment by flamewave000** [comment]
I've done a soft release as v1.1.1. Could you update the module and let me know if the issue is fixed?

**Comment by DarKDinDoN** [comment]
@flamewave000 after updating and changing some settings in the module settings, the /log command is not working anymore.
The strange thing is that FVTT is not asking for a reload anymore (after changing and saving parameters).
I don't see any relevant errors in the console.

**Comment by flamewave000** [comment]
This should be corrected in the latest 1.1.2 release. As part of trying to fix your issue, I changed "when" the module would initialize when Foundry is loading. It became a race of which module would initialise first. This should be resolved now.
