### ISSUE TITLE
[DF Settings Clarity]: Menus show scope wrong

### ISSUE THREAD

**Issue by mkahvi** [flamewave000/dragonflagon-fvtt#52]
**Module**
Settings Clarity 2.1.2

**Describe the issue**
Anything created with game.settings.registerMenu() shows player/GM scope wrong. This is very likely caused by them not using scope and instead being dictated by restricted setting instead.

You can see this happen, for example, with core permission configuration.

**Expected behavior**
The symbols matching the restricted setting.

**Screenshots (Optional)**
GM view:  
![Screenshot 2021-02-18 150449](https://user-images.githubusercontent.com/8120158/108361117-bfe2b300-71fa-11eb-87b9-1f42c2749fe9.png)

Player view of the same:  
![Screenshot 2021-02-18 150439](https://user-images.githubusercontent.com/8120158/108361134-c4a76700-71fa-11eb-9df2-640174d8fad0.png)

**Comment by flamewave000** [comment]
Should be fixed in v2.1.3
