### ISSUE TITLE
[DF Chat Enhancements]: /log command not recognized

### ISSUE THREAD

**Issue by davidR1974** [flamewave000/dragonflagon-fvtt#53]
**Module**
DF Chat Enhancement 1.1.1 (dependency Chat Command 1.3.0)
tested with Chrome (on one system) and Foundry app+Chrome (on other system)

**Describe the issue**
/log command in not recognized and returns message : 
"/log is not a valid chat message command."

**To Reproduce**

I created a new dnd5 world on 2 systems with only DF Chat Enhancement & Library Chat Command activated. 
Same module settings.
Same name of journal for log target

On one system ==> /log command is not recognized
On other ==> /log command is recognized

the only difference i can see is one is running on node.js/Unix and the other on Windows.
Also i checked at .js scripts and they are all on one line (No CR between lines of code). Don't know if that may be a cause of the issue.

EDIT  : Seems i can make it work by starting with 'Adventure Log : Enabe' unchecked then checking it after the world starts..

**Expected behavior**
/log command should be recognized

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/77006061/108548513-36aba900-72ec-11eb-85af-56533448ddf0.png)

![image](https://user-images.githubusercontent.com/77006061/108548850-aa4db600-72ec-11eb-8e48-0dc92f1a93ff.png)

**Comment by megahead11** [comment]
I've also experienced this issue but it's mildly intermittent. 
Something I've noticed when this happens is that the "/log" command appears when the enable log option is disabled (but it doesn't work), but disabling the option makes the /log command vanish. 

Half of the time it will work until I close  the world, and then once I re-open it, the command stops working. I think there may be something wrong with how the /log command is registering in the library.

**Comment by davidR1974** [comment]
Yeah .. retested with that in mind..
Seems i can make it work by starting with 'Adventure Log : Enabe' unchecked then checking it after the world starts..

**Comment by flamewave000** [comment]
Sorry folks, I changed the point in Foundry's lifecycle where the logger gets initialised. The Chat Commands library initializes in the same phase that I've moved to, which means if ChatCommands happens to get initialised first, Chat Enhancements will not be able to register its command.

This should now be fixed in v1.1.2
