### ISSUE TITLE
DF Chat Enhancement: Separate logs for GM

### ISSUE THREAD

**Issue by MaximeTKT** [flamewave000/dragonflagon-fvtt#54]
**Is your feature request related to a problem? Please describe.**
Right now, all players including GM are logging to one singe journal entry

**Describe the solution you'd like**
It would be nice to have another journal entry for the GM to log to.
This way, players can have their own journal entry and GM can still log entries for campaign management (things that players shouldn't see)

**Comment by flamewave000** [comment]
I think the simplest way to do this is to add an additional command for GMs only `/gmlog`
