### ISSUE TITLE
DF Settings Clarity: Client-side menus lack icon

### ISSUE THREAD

**Issue by mkahvi** [flamewave000/dragonflagon-fvtt#55]
**Module**
DF Settings Clarity v2.1.3

**Describe the issue**
Client-side settings menus no longer show any icon.

**Screenshots (Optional)**

![missing-client](https://user-images.githubusercontent.com/8120158/108596181-159a9500-738c-11eb-9a67-8c0e84d28495.png)

**Comment by flamewave000** [comment]
Unfortunately some of these settings do not have a restricted/scope flag which makes it impossible for me to determine if they are client or world settings. This was recently discovered while fixing the menu button indicators.

**Comment by mkahvi** [comment]
Scope defaults to client in foundry.js explicitly.

Restricted similarly defaults to false, I think, but it's not explicit.
