### ISSUE TITLE
DF Curvy Walls: Sub menu buttons won't go away

### ISSUE THREAD

**Issue by jrdstauffer** [flamewave000/dragonflagon-fvtt#62]
**Module**
DF Curvy Walls v1.3.4

**Describe the issue**
After clicking on the curve options in the Wall Controls the + / - sub menu buttons display and won't go away when clicking on another menu item (e.g. Basic Controls ). This also happens after placing a wall segment except with the + / - / apply / clear / couple sub menu buttons.

**To Reproduce**
See description.

**Expected behavior**
Buttons to go away.

**Screenshots (Optional)**

**Comment by jrdstauffer** [comment]
Wanted to note that this even happens with no modules loaded except for DF Curvy Walls ( and Tidy UI ).

**Comment by flamewave000** [comment]
Thanks for reporting this. It must have happened in one of my updates and I never noticed. I'll look into it sometime this week. I have to do some revisions on the module anyway (it also seems to cause a memory spike).
