### ISSUE TITLE
DF Chat Enhancements - non-gm users cannot log chat messages to the journal

### ISSUE THREAD

**Issue by tposney** [flamewave000/dragonflagon-fvtt#67]
**Module**
DF Chat Enhancements

**Describe the issue**
In my game world when users try to log to the players log they get "user does not have permission to update journal entry <ID>".
In my test world (same modules enabled) I do not get this problem. I am at a loss to guess what is different between the two worlds that would cause this problem.

In my game world, I created a journal entry, gave all users owner permission (they are normal users, not trusted) and I get the error. In my test world I did (as far as I can tell) the same thing, but logging chat cards to the player log works perfectly.

Are there any gotchas I should be aware of?

**Comment by flamewave000** [comment]
This sounds like the issue is that the players do not have permission to edit the Journal you have set as the Adventure Log. Can you make sure they are set as `Owner` and not `Observer`? Observers cannot edit the journal, only look at it.

**Comment by tposney** [comment]
That's what I had assumed, but I confirmed that the user in question has
OWNER permission of the journal entry and can edit the journal by hand.
I should also mention that in my test world the module works fine. It is
only the production world that is a problem.
I get, what looks like, the standard foundry error message that the user
does not haver permission to edit the journal entry and a journal entry id.

**Comment by flamewave000** [comment]
Yeah, that error is sent by FoundryVTT and not DFCE. I figured it best to not interfere with the natural permissions handling. Basically it sounds like FoundryVTT does not think your player has permission to edit the file. I haven't been able to reproduce the issue. I'm testing Foundry on both the Windows Desktop App and the Linux Hosted Server.

**Comment by tposney** [comment]
"Hangs head in shame". It was user error, and pretty stupid user error at that. So let's just pretend it was never raised.

**Comment by flamewave000** [comment]
PEBKACs happen to all of us 🤣
