### ISSUE TITLE
DF Manual Rolls: Compatibility issue with Quick Rolls

### ISSUE THREAD

**Issue by nulmas** [flamewave000/dragonflagon-fvtt#70]
**Module**
DF Manual Rolls v1.2.0

**Conflicting Module**
Quick Rolls v1.5.4

**Describe the conflict**
Whenever the two modules are activated, neither will be able to do damage rolls. This happens even if "Force Manual Rolls" is unchecked.

**To Reproduce**
1. Install both modules;
2. Make any attack;
3. Attempt to roll for damage using the card in the chat window.

**Expected behavior**
Damage should be rolled.

**Comment by flamewave000** [comment]
Was this working previously? Just want to know if this was caused by my recent flavour text update.

**Comment by nulmas** [comment]
I have no idea, sorry.

I only just started using Foundry and I've been testing all the modules I may want to use. I checked this using Find the Culprit.

I don't even intend on using Quick Rolls, but I figured I should let you know.

**Comment by flamewave000** [comment]
This appears to be a partial conflict. By disabling the DnD5e flavour text feature, the conflict goes away. I am releasing a minor bug fix that adds the ability to disable this feature in the settings.
