### ISSUE TITLE
DF Manual Rolls: lib Wrapper, Skill Customization for 5e, Token Action HUD, Tool Proficiencies for DnD5e

### ISSUE THREAD

**Issue by Battenhatch** [flamewave000/dragonflagon-fvtt#71]
**Conflicting Module(s)**
- DF Manual Rolls
- libWrapper
- Skill Customization for 5e
- Token Action HUD
- Tool Proficiencies for DnD5e

**Describe the conflict**
When DF Manual Rolls is activated along these other modules, the error "Canvas Drawing Failed for the TokenLayer. See the console for details.". This prevets many behaviours, as the tabletop is malformed. Eg. conditions markers fail to display, targeting of tokens not possible.

**Expected behavior**
No error

**Comment by flamewave000** [comment]
Caused by the DnD5e Flavour text feature. Follow the same workaround as was developed for #70.

This issue will hopefully be fixed after the next version of DnD5e is released

**Comment by flamewave000** [comment]
Ticket in DnD5e that this issue is blocked by:
https://gitlab.com/foundrynet/dnd5e/-/issues/962
