### ISSUE TITLE
DF Chat Enhancer: Adventure Log change

### ISSUE THREAD

**Issue by Gossetjr** [flamewave000/dragonflagon-fvtt#73]
**Chat log read top to bottom.**
I'd love a toggle of some kind to be able to make it that when a /log is added it is placed at the top of the Adventure Log that it saves to above the previous entry. The log gets pretty long and the most relevant info is always at the bottom as it is right now.

Thanks you.

**Comment by flamewave000** [comment]
I've completed the work for this and it will be in the next release.

**Comment by Gossetjr** [comment]
Checked it out. Exactly what I had in mind. Works like a charm.

Thank you.
