### ISSUE TITLE
DF Hotkeys: Provide shim to avoid hard dependency

### ISSUE THREAD

**Issue by manuelVo** [flamewave000/dragonflagon-fvtt#77]
I really like idea of libWrapper to provide a shim that modules can use to avoid declaring a hard dependency to libWrapper. It would be great if DF Hotkeys could do the same. This is especially desirable because foundry cannot manage dependency chains. If module A depends on module B, which in turn depends on DF Hotkeys, then enabling module A won't enable DF Hotkeys and the whole thing will break. A shim would allow the modules to continue working in that case.

The shim could be a small portion of code that checks if DF Hotkeys is installed. If so it does nothing. If not, it registers the same interface as DF Hotkeys, but only registers hotkeys using their default binding, without offering configuration options to the user. I think it's important here to keep the code as minimal as possible to avoid cluttering the code bases of people using the shim.

**Comment by flamewave000** [comment]
I can probably add a shim file as part of my build process. It would include just the Hotkeys and Keys classes. I'll see what libWrapper does to get their shim to self initialize.

**Comment by flamewave000** [comment]
Alright, I got this working tonight. My gulpfile.js is getting to be a very intense part of my module haha.
The next release will come with the following 2 files that can be included in any Module to avoid a hard dependency on the library.
```
lib-df-hotkeys.shim.js     <-- Shim Code File
lib-df-hotkeys.shim.d.ts   <-- Shim Type Definitions for TypeScript
```
