### ISSUE TITLE
DF Hotkeys: Option to block/allow repeated events

### ISSUE THREAD

**Issue by manuelVo** [flamewave000/dragonflagon-fvtt#79]
The javascript event contains a field called `repeat` that indicates whether the fired event is an repeated event (if you press a key for a prolonged period of time the event will fire periodically. `repeat` will be set to `false` for the first event and `true` for every event fired after that until the key is released). For some hotkeys having repeated events may make sense (arrow keys being an example - the token will move until the arrow key is released), while for others it is counterproductive (having a ctrl+v event repeat will only clutter the scene uncontrollably).

For this reason I think when registering a hotkey it would be nice if it was possible to define whether repeated events should be allowed or blocked.

**Comment by flamewave000** [comment]
Currently I am ignoring repeats, but I see your point and will add this in 👍🏽
