### ISSUE TITLE
DF Manual Rolls: First roll input with Enter produces two chat messages

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#80]
**Module**
DF Manual Rolls 1.2.1

**Describe the issue**
This is a very minor bug, almost not worth reporting :stuck_out_tongue: 
If the setting **Flag manual rolls** is activated, the first roll that is input using **Enter** produces two chat messages: One with the flag and one without. Pressing the Trash can on either of them removes both messages.

Note:
- Bug only manifest if input is confirmed with Enter. Pressing OK button with the mouse works fine.
- Subsequent rolls work as expected, until an F5.
- Tested in a clean world, with only DF Manual Rolls active.

**To Reproduce**
1. Activate **Flag manual rolls**
2. Reload World with F5
3. Make an attack/roll
4. Enter the result and press Enter to confirm the dialog
5. Two chat messages are created.

**Expected behavior**
Only one, flagged message.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/10401440/111300456-659a0e00-8651-11eb-8a6b-1772bb0e418a.png)

**Comment by flamewave000** [comment]
This is interesting. I will have to investigate it. I definitely want users to be able to hit Enter to submit and Esc to cancel (which are default behaviours for prompts). It makes it much easier to use the prompt without having to grab the mouse and click a button.

**Comment by flamewave000** [comment]
Hey, I was just testing this out and I'm not able to reproduce the issue. What other mods do you currently have installed? It seems like one of them is likely conflicting.

**Comment by plutoneld** [comment]
No other modules, i tested in a clean world before reporting (as mentioned).

I can test again in a while, but remember that this was only for the absolute first message after having Flags activated and reloading the world.

**Comment by plutoneld** [comment]
I reproduced it like so:
* Edit World, reset active modules
* Enable DF Manual Rolls
* Settings as screenshot attached
* **First** roll like screenshot, input confirmed with Enter

Note that if I press F5 after the roll, the message _not_ flagged as manual disappears. And _all rolls after this first roll_ works as intended, confirming with mouse or enter.

I had trouble reproducing the bug after these initial steps. I'm gonna try closing Chrome and start it again with the same steps, and post back.

![image](https://user-images.githubusercontent.com/10401440/113176822-2f61ae80-924d-11eb-901e-34330b419665.png)

![image](https://user-images.githubusercontent.com/10401440/113176925-486a5f80-924d-11eb-89e7-b4489e11756b.png)

![image](https://user-images.githubusercontent.com/10401440/113177408-c464a780-924d-11eb-84db-d3f19327c4da.png)

**Comment by flamewave000** [comment]
Thank you for the very detailed repro steps. I'll have to take a look this weekend and see if I can get to the bottom of it 👍🏼

**Comment by flamewave000** [comment]
Ok, so it took a little while to get this figured out, but I think I've found what is causing this. Basically the two messages you see are the same message. I'm detecting the message creation and appending the (Manual Roll) to the flavour text. That update is somehow causing Foundry to display the message twice. I'll see if I can somehow prevent this with like a delay or something.

**Comment by plutoneld** [comment]
Can not reproduce this in FVTT 0.8.6, DF Manual Rolls 2.0.0!

**Comment by flamewave000** [comment]
I was just going come and ask this morning if this issue could be reproduced. Happy to close the ticket 👍🏽
