### ISSUE TITLE
DF Chat Enhancement: Expose Adventure Log API ~Respond correctly to chat messages sent via API/Macro~

### ISSUE THREAD

**Issue by brother-oak** [flamewave000/dragonflagon-fvtt#81]
If you send a message to chat using an API (e.g. from a script macro) and it starts with "/log", this is not trapped and sent to the log file, but is instead just displayed as a chat message.

I would find this useful as I would set up macros to log different things that I can enter via dialog entry ("/log Start of Session 42"), or via token selection ("/log PLAYER1 attempts to hit WEREWOLF") etc, with the macro prepending the "/log" and sorting out the rest of the chat message based on token selection, dialog entry etc, etc.

However, since the API ChatMessage.create() seems to bypass DF Chat Enhancement, this idea doesn't currently work.

I'm guessing this may not be easy as you may not be able to intercept API messages in this way, but I thought I'd ask :-)

**Comment by flamewave000** [comment]
So unfortunately I won't be able to fix this here. I am using the Chat Commands library for capturing the /log command. This issue will need to be reported there. I can open the ticket and reference this one you've made.

**Comment by flamewave000** [comment]
I've reported the issue here: [Chat-Commands-Lib: Issue #6](https://github.com/League-of-Foundry-Developers/Chat-Commands-Lib/issues/6)

In the meantime, a possible feature suggestion would be for me to expose my own API for logging Events to the Adventure Log. Maybe something like `ui.adventurelog.addEvent(...)`

**Comment by brother-oak** [comment]
Thanks for reporting that - appreciate it.

Exposing your API would be really excellent - I'd definitely hope to make use of that, as the log file is what I'm after (rather than the edit of chat messages etc)

**Comment by flamewave000** [comment]
I'm releasing v3.0.0 which will have the following available for Macros

```javascript
// Log an Event to the Adventure Log
AdventureLog.event("Something happened!")
// (GM Only) Log an Event to the GM Adventure Log
AdventureLog.gmevent("The players did something!")
// Log a Quote to the Adventure Log
AdventureLog.quote("Bob", "Don't worry, be happy!")
// (GM Only) Log a Quote to the GM Adventure Log
AdventureLog.gmquote("Bob", "Don't worry, be happy!")

// If you want the event/quote posted to the chat, add "true" to the call
AdventureLog.event("Something happened!", true)
AdventureLog.quote("Bob", "Don't worry, be happy!", true)

// (GM Only) GM logs will be whispered to yourself
AdventureLog.gmevent("The players did something!", true)
AdventureLog.gmquote("Bob", "Don't worry, be happy!", true)
```
