### ISSUE TITLE
DF Hotkeys: Allow `default` to be a static value, infer setting storage location, to HotkeySetting interface

### ISSUE THREAD

**Issue by Varriount** [flamewave000/dragonflagon-fvtt#82]
While I feel like the current API for DF Hotkeys has a good balance between flexibility/power and simplicity, I feel that the current API could be slightly modified to cater to the most common use-cases.

Currently, the API requires function types for the `get`, `set`, and `default` members. I feel that, for 90% of use-cases, these fields are going to be something like this:
```js
//  (stolen from the examples in the documentation)
hotkeys.registerShortcut({
	name: `${MODULE_SCOPE}.my-hotkey`,
	get: () => game.settings.get(MODULE_SCOPE, 'my-hotkey'),
	set: async (value: KeyMap) => await game.settings.set(MODULE_SCOPE, 'my-hotkey', value),
	default: () => { return { key: hotkeys.keys.KeyQ, alt: false, ctrl: false, shift: false }; },
	// ...
});
```
So, it would be convenient if the API optimized for the common use-case, and allowed something like:
```js
hotkeys.registerShortcut({
	name: `${MODULE_SCOPE}.my-hotkey`,
	default: {
		key: hotkeys.keys.KeyQ,
		alt: false,
		ctrl: false,
		shift: false
	},
});
```
The library would default to using the `name` property to store and retrieve a setting for the hotkey in client-scoped settings, and allow a static value for the `default` property.

Some alternatives/idea:
  - Allow a 2-element array for `name`
  - Have a `registerSettingBackedShortcut` function (although the name is a tad long)

**Comment by flamewave000** [comment]
Yeah I initially was concerned about managing the settings myself, but it seems like something most people would likely prefer to save them hassle. I currently use a Settings helper that makes implementing this super simplistic, but certainly worth changing. I'll see if I can get this in with the next release, I'm going to be focusing on building a Shim for it that modules can include per the suggestion in #77
