### ISSUE TITLE
DF Hotkeys: conflict with Quick Insert

### ISSUE THREAD

**Issue by ben** [flamewave000/dragonflagon-fvtt#84]
### Conflicting Module(s)
- [Quick Insert](https://gitlab.com/fvtt-modules-lab/quick-insert)

### Describe the conflict
- Install DF Hotkeys and Quick Insert, both with default settings
- Open quick insert with ctrl+space
- Type "stone"
- Result: the `s` key is intercepted by DF Hotkeys, so the quick-insert box ends up with "tone" in it

### Expected behavior
The word "stone" should be typed in the quick-insert search bar

Not completely sure where the problem lies, so I'm filing an issue on both projects. [Link](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues/47)

**Comment by flamewave000** [comment]
Thank you for you report!
This issue should already be fixed in the latest version 2.1.0. Please update the module and try to reproduce.

**Comment by ben** [comment]
Looks fixed to me. Thanks!
