### ISSUE TITLE
DF Curvy Walls: Certain mod's text fields fails to recognize the delete button.

### ISSUE THREAD

**Issue by ExileofBrokenSky** [flamewave000/dragonflagon-fvtt#86]
**Module**
DF Curvy Walls v2.1.0
Tidy5e Sheet 0.4.24
Quick Insert - Search Widget 2.4.4

**Describe the issue**
The Delete key is ignored when pressed while editing certain text fields from various other mods.

**To Reproduce**
Steps to reproduce the behavior for tidy5e sheet:
1. Open any actor sheet
2. Set the sheet to use dnd5e.Tidy5eSheet
3. Type anything in the top most text field, (the one to name the actor.)
4. Move cursor back and press the delete key
5. Nothing happens.

Steps to reproduce the behavior for Quick Insert:
1. Summon the search field.
2. Type anything.
3. Move the cursor back  and press delete.
4. Nothing happens.

**Expected behavior**
The text at the cursor to be deleted.

**Notes**
No errors show in the console.
Ctrl-Delete still works to delete the entire word in the situations above.
In most other text fields delete works fine. For instance, in the Item name text field (using dnd5e.Tidy5eItemSheet) it works fine, as it does in most large bulk text fields.
Used Find-The-Culprit to isolate the issue to this mod. In the other mods listed the delete key has always worked and only presents this issue when DF Curvy Walls is active.
The issue persists whether or not lib-wrapper or DF hotkeys is on or off

**Comment by flamewave000** [comment]
So this is an issue due to Curvy Walls' Hotkeys shim. If you install and activate "Library: DF Hotkeys" this issue will be fixed as it corrects the problem. The next version of curvy walls will likely require this library as a hard dependency.

**Comment by ExileofBrokenSky** [comment]
Is that a upcoming version fix? I have Library: DF Hotkeys active and the issue persists.

**Comment by flamewave000** [comment]
Ok, so I just looked into this. It appears these fields are not using the expected Input or TextArea html elements. Instead they're making the elements "editable". Hotkeys does not currently account for this (mainly because I never knew you could do that with an HTML element lol). I'll look into making Hotkeys check for that property and handle them like it currently does for Input and TextArea. Thanks!
