### ISSUE TITLE
DF Chat Enhancement: Archived logs between worlds are mixed somehow

### ISSUE THREAD

**Issue by JJBocanegra** [flamewave000/dragonflagon-fvtt#87]
**Module**
DF Chat Enhancement v2.1.0

**Describe the issue**
I have been archiving the chats using names like "session 10" in both worlds I'm currently a DM. Just today I realised that the chat archives were mixing between worlds, and the last named session I used was overwriting the one with the same name in the other world I.E.: In LMoT I archived a chat named "Session 9" and the next day in BGDIA I archived a chat name "Session 9", with this I lost the LMoT archived chat and was overwritten by the BGDIA one...

I just named differently the sessions chats to have a look at what I lost in each world and this is the result

LMoT world:
![image](https://user-images.githubusercontent.com/5797636/112144222-33505980-8bd9-11eb-9013-41b41a1f21ed.png)
Here I realised the error and archived the chat with the "LMoT" prefix.

BGDIA world:
![image](https://user-images.githubusercontent.com/5797636/112144242-39463a80-8bd9-11eb-9eb7-05090ff7d4ee.png)

**To Reproduce**
1. Have two worlds.
2. Archive a chat in first world with name "Foo".
3. Archive a chat in second world with name "Foo".
4. First world archived chat is lost.

**Expected behavior**
Each world should have their own archived chats and not be shared between worlds.

**Comment by flamewave000** [comment]
Thank you for reporting this. It's not so much a bug, as more just something that was intentionally prevented. I will convert it to an enhancement request, and include it with the work being down for better archive storage.

**Comment by flamewave000** [comment]
I'm not sure how you are seeing this kind of issue, but I am currently unable to reproduce it. I have two worlds on the same server, and switching between them I only see the archives for the world I'm in. The Archives are stored in the World settings, so it shouldn't be possible for those to be shared.

What version of Foundry are you using?

**Comment by JJBocanegra** [comment]
I'm using FoundryVTT v0.7.9.

It's strange that it isn't happening, maybe the cause of it is that I export the world settings using "[Forien's Copy Environment](https://github.com/Forien/foundryvtt-forien-copy-environment)" module and import them in the other world. I do this because if I change some midiqol settings for example, I want it to be the same in the other worlds and I'm constantly exporting and importing.

Doing this may cause the problem. I could test it later or maybe tomorrow ;)

**Comment by brother-oak** [comment]
I've just tested this out on my system (I originally thumbed up the issue as this would cause me a problem, though I haven't started using the log files in anger yet).
I'm using 0.7.9 hosted on The Forge.
I created a chat archive in one world (called Session 99) and went to another world - I couldn't see this archive in the archive list. I created an archive in this world using the same name and it was visible in that world. Back to the first world and view the Session 99 archive and it was the correct (original) one.

So I am not seeing this problem either. I'm not using Forien's Copy Environment module though

**Comment by flamewave000** [comment]
@JJBocanegra That is exactly the issue. The chat archive registry is stored in the World Settings. So if you cloned them to a new world, you would see all of the chat archives from the old world.

**Comment by JJBocanegra** [comment]
There is no way to save the archived chats in an external JSON for example? It would prevent this.

**Comment by flamewave000** [comment]
Yes and no. I am still storing a registry for the chats in the settings which keeps the meta information. The files just store all the Chat Messages themselves as those are very bloated and can potentially take up a lot of space.

**Comment by JJBocanegra** [comment]
I though about that last message, and I want to suggest:

What about storing that data inside the generated files? You store in the JSON file directly all the messages, but what if that JSON file contains the information that you are storing in the settings? Like:
```json
{
  "id": 1,
  "name": "foo",
  "visible": true,
  "messages": [...]
}
```

With this, you can remove the settings modifications anymore, just create the files and load all of them, and set the settings for each one.
