### ISSUE TITLE
DF Hotkeys, Allow another module to add a config button just for that modules group.

### ISSUE THREAD

**Issue by ironmonk88** [flamewave000/dragonflagon-fvtt#92]
I have a bunch of keys registered to a group, but I'd like to add a button to my modules config section to open up the Hotkey Libraries key config screen, but only show my group.
Essentially, it might not be clear that I have hotkeys registered, and that users have to look in a completely different module to set them.  I'd like to just show my set of hotkeys from my modules config section.

**Comment by flamewave000** [comment]
I like this idea. Basically just a group filter for the HotkeysConfig. I'd make it a list of group ids and a list of hotkey ids. That way you can have even more granular control and even show some Hotkeys from the "General" section.

**Comment by ironmonk88** [comment]
Ohhhh... I like that.  Even better.

**Comment by flamewave000** [comment]
I've got the filtering working 👍🏽 
![image](https://user-images.githubusercontent.com/3588046/112701896-3d3bbc00-8e68-11eb-89ef-6e3400535368.png)
