### ISSUE TITLE
DF Scene Enhancements: Navigate from Journal causes all Journal links to ignore permissions

### ISSUE THREAD

**Issue by bheiskell** [flamewave000/dragonflagon-fvtt#93]
**Module**
DF Scene Enhancement and v3.3.2

**Describe the issue**
When the `Navigate when a Scene reference is clicked in a Journal` option toggled on, links from one Journal to another bypass journal permission checks.

This is a pretty serious issue with my workflow, as players were able to access GM only notes accidentally when clicking on a link included in a Journal that I shared with them.

**To Reproduce**
1. Install FoundryVTT 0.7.9
2. Install and activate DF Scene Enhancement v3.3.2
3. Create a player to test with, and log in using a private window
4. As the GM, create two journals (`journal 1` and `journal 2`)
5. Edit `journal 1`
6. From the Journal Entries side bar, drag `journal 2` into the contents of `journal 1`.
7. Save `journal 1`
8. Click `Show Players`
9. As the player, you should now see `journal 1` with a link to `journal 2`
10. Click `journal 2`

**Expected behavior**
When you click `journal 2` you should receive an error: "You do not have permission to view this JournalEntry sheet."

To see the correct behavior, go to the module settings and uncheck the first option.

**Screenshots**
As the GM
![image](https://user-images.githubusercontent.com/96167/112780903-cba27000-9017-11eb-96be-bc40dd4d31ff.png)

As the player, showing `Entry 2` after having clicked it from `Entry 1`. The Player does not have access to either of these Journals and was only able to see `Entry 1` because I clicked Show Players.

![image](https://user-images.githubusercontent.com/96167/112780991-fd1b3b80-9017-11eb-9f61-c3a11569dc8a.png)

No errors were in the console.

**Comment by flamewave000** [comment]
Thank you for reporting this issue. I'll have to take a look and get it fixed. Unfortunately this week is a bit busy for me, so I may not be able to get a fix in until the weekend.

**Comment by flamewave000** [comment]
I just pushed out v3.3.3 that should have this fixed. Please try it out and let me know if you have any more issues 👍🏽

**Comment by bheiskell** [comment]
@flamewave000, sorry for the delay. I wasn't able to test until today. It looks great! Thanks!
