### ISSUE TITLE
df-chat-enhance: cannot update chat archive name

### ISSUE THREAD

**Issue by malexherron** [flamewave000/dragonflagon-fvtt#94]
**Module**
df-chat-enhance 3.0.1

**Describe the issue**
chat archives name changed do not save permanently

**To Reproduce**
1. Go to 'Manage chat archive'
2. Edit name of archive and save
3. Close chat archive display
4. Chat Archive Manager does not display updated name

**Expected behavior**
Once saved, chat archive manager should retain saved name update.

**Screenshots (Optional)**
![Screen Shot 2021-04-01 at 4 34 03 PM](https://user-images.githubusercontent.com/81781423/113364360-21249880-9308-11eb-8d65-1811b76e5351.png)

**Comment by DOMtheDM** [comment]
I noticed today you also can't update the visibility checkbox either. It doesn't save.
