### ISSUE TITLE
DF Chat Enhance: archive created in 3.0.0 not visible in 3.0.1

### ISSUE THREAD

**Issue by malexherron** [flamewave000/dragonflagon-fvtt#95]
**Module**
df-chat-enhance 3.0.1

**Describe the issue**
Had issues with chat archives unable to open in 3.0.0, bug was found by hmqgg and hotfixed. Archive created in that version is not seen in chat archive manager in 3.0.1. JSON is present in foundry filesystem

**To Reproduce**
*Unsure how to reproduce*
1. Created archive in 3.0.0
2. Title was blank and archive could not be opened by module
3. update module to 3.0.1
4. chat archive now empty
5. verify presence of archive json in worlddata/chat-archive

**Expected behavior**
Archive from previous version should be present and browse-able by current version

**Screenshots (Optional)**
![Screen Shot 2021-03-24 at 11 21 28 PM](https://user-images.githubusercontent.com/81781423/113364667-fa1a9680-9308-11eb-8503-f893ed315bda.png)
Screenshot shows archive with error as displayed in 3.0.0

![Screen Shot 2021-04-01 at 4 41 37 PM](https://user-images.githubusercontent.com/81781423/113364762-27ffdb00-9309-11eb-8695-dbb0c6a6063d.png)
screenshot shows only archive created in 3.0.1, and not the archive created in 3.0.0

![Screen Shot 2021-04-01 at 4 43 12 PM](https://user-images.githubusercontent.com/81781423/113364836-62697800-9309-11eb-8330-089fa689e716.png)
screenshot showing presence of 3 archives in filesystem

**Comment by flamewave000** [comment]
Is this still an issue? I'm not currently able to reproduce it.

**Comment by malexherron** [comment]
yes, issue remains after updating to 3.0.2, i see the json file from the missing archive(s) and but it does not appear in the chat archive.  i have attached an example of a missing JSON (renamed as .txt) in case it helps.

is there a way to manually load a chat archive json into the chat manager?

[2_Test.txt](https://github.com/flamewave000/dragonflagon-fvtt/files/6307113/2_Test.txt)
