### ISSUE TITLE
DF Curvy Walls: Add more sophisticated methods of defining a circle

### ISSUE THREAD

**Issue by manuelVo** [flamewave000/dragonflagon-fvtt#99]
**Is your feature request related to a problem? Please describe.**
Tracing circular walls is currently a relatively painful process, becasue the circle in Curvy Walls is defined by the corners of a square that is drawn around the circle. This makes it necessary to make good guesses about where to place the point, iterating multiple times on the edge positions until the circle is just about right.

**Describe the solution you'd like**
Mathematically a circle can be fully described by two or three points. That is either:
- The center of the circle plus one point on the circle
- Three points on the circle

The same goes for Circle arcs, which can be fully described using three points which can be either:
- The center of the circle and the start and end points of the arc on the circle
- The start and end points of the arc on the circle plus another point on the circle

It would be great if Curvy Walls supported these methods to describe circles and circle arcs. That way it would be possible to directly trace the circle on the map instead of guessing where the corners of the box have to go so the circle will sit at the right location.

I think doing the same would be possible for ellipses - probably requiring more points to be specified - as well.

**Comment by flamewave000** [comment]
First, I want to preface this with the following: "I absolutely despise this ticket"... I spent 3 hours tonight trying to approximate a Cubic Bezier curve given 4 points. It broke my brain and I couldn't get anything useable. Turns out Cubic curves can not be mathematically approximated. They can only be interpolated using complex algorithms that are slow and only available in C++ libraries 😩

Second, I now have a much better method of generating Quadratic Curves by approximating. You can also now plot 2-4 points to generate a rectangle.

Third, I am currently having great difficulty with the ellipse. From what I can understand, you can only generate a perfect circle when you only have 2-3 points of data. I have yet to find an equation that allows the calculation of an XY axes aligned ellipse from 4 points of data where you do not know the center of the ellipse.

**Comment by manuelVo** [comment]
Thanks for giving this a shot and sorry for causing you so much headache with this reqeust. Admittedly I actually expected this issue to never even get looked at because it's fairly complicated, so kudos for trying (and for getting as far as you got!).

I think the breizer curves don't necessarily need a point approximation method. The way breizers are defined currently "using start and end point and a 'curve indicator'" is very usable in my opinion, so I think skipping on that would be a good option if it's that difficult to do.

As for the ellipse, I think you'll need 5 points to fully describe an ellipse. I've found various resouces on how an ellpise can be constructed from 5 points (one even with an example implementation, but sadly in lisp), but they are a bit too mathsy for me to grasp. Maybe they are of more use to you?

https://math.stackexchange.com/questions/163920/how-to-find-an-ellipse-given-five-points
http://www.lee-mac.com/5pointellipse.html
https://en.wikipedia.org/wiki/Five_points_determine_a_conic

**Comment by flamewave000** [comment]
Thank you for looking into it. Yeah it does appear that you need precisely 5 points as a minimum to generate an ellipse. If you only have 4 points, you get an infinite number of ellipses. I'm actually considering changing the system so you can define a circle as I currently have it, but also place a series of control points to create an ellipse that can essentially rotate to any angle. But that might be a little overkill for what this module is meant to solve.

It's not normal for there to be elongated ellipses in a map that are not parallel to the X and Y axes. So like a ship map would typically always be vertical or horizontal. It would be fairly niche I think.

**Comment by flamewave000** [comment]
I am refraining from doing the ellipse from 5 points. It's doable, but more complex than I have the time to implement and would require supporting a rotated ellipse, which adds a whole order of complexity to the tools (mainly why I haven't tackled #109).
